// 2026 초등 사회과 세계 지리 학습용 전체 데이터셋 (총 210개국)
// 대륙별 주요국을 앞부분에 배치하고, 나머지 국가를 뒷부분에 배치하였습니다.
window.WORLD_DATA = [
  // ==========================================
  // --- 아시아 (Asia) - 총 60개국 ---
  // ==========================================
  // [주요국 14개국 선두 배치]
  {
    code: "kr",
    name: "대한민국",
    engName: "South Korea",
    capital: "서울",
    engCapital: "Seoul",
    continent: "아시아",
    location: "아시아 동부 한반도에 위치",
    trivia: "삼면이 바다로 둘러싸여 있으며, 독창적인 한글과 세계적인 IT 산업, K-팝 등의 한류 문화가 빛나는 나라입니다.",
    landmarks: ["경복궁", "남산서울타워", "제주도"]
  },
  {
    code: "cn",
    name: "중국",
    engName: "China",
    capital: "베이징",
    engCapital: "Beijing",
    continent: "아시아",
    location: "아시아 동부에 위치",
    trivia: "세계 최대 인구를 가졌으며 역사 유적이 풍부하고 인류 최고의 성벽인 만리장성을 품고 있는 거대한 영토의 나라입니다.",
    landmarks: ["만리장성", "자금성", "병마용갱"]
  },
  {
    code: "jp",
    name: "일본",
    engName: "Japan",
    capital: "도쿄",
    engCapital: "Tokyo",
    continent: "아시아",
    location: "아시아 동부 태평양의 섬나라",
    trivia: "네 개의 큰 섬과 수많은 화산 지형으로 이뤄진 나라로 활화산인 후지산과 맛있는 초밥, 온천이 발달했습니다.",
    landmarks: ["후지산", "금각사", "도쿄타워"]
  },
  {
    code: "in",
    name: "인도",
    engName: "India",
    capital: "뉴델리",
    engCapital: "New Delhi",
    continent: "아시아",
    location: "남부 아시아 인도양 연안에 위치",
    trivia: "다양한 종교와 문화를 가졌으며 세계 7대 불가사의인 아름다운 무덤 타지마할과 향신료 카레가 상징적입니다.",
    landmarks: ["타지마할", "갠지스강", "자이푸르 핑크시티"]
  },
  {
    code: "vn",
    name: "베트남",
    engName: "Vietnam",
    capital: "하노이",
    engCapital: "Hanoi",
    continent: "아시아",
    location: "인도차이나 반도 동부에 위치",
    trivia: "남북으로 긴 국토를 가졌으며 쌀국수와 맛있는 베트남 커피, 절경인 하롱베이 관광지로 인기가 많습니다.",
    landmarks: ["하롱베이", "호이안 올드타운", "구찌 터널"]
  },
  {
    code: "th",
    name: "태국",
    engName: "Thailand",
    capital: "방콕",
    engCapital: "Bangkok",
    continent: "아시아",
    location: "인도차이나 반도 중앙에 위치",
    trivia: "불교 문화가 국민 생활 전반에 스며있으며 맛있는 톰얌쿵과 길들여진 코끼리 축제가 널리 알려졌습니다.",
    landmarks: ["방콕 왕궁", "왓 아룬 사원", "치앙마이 올드타운"]
  },
  {
    code: "ph",
    name: "필리핀",
    engName: "Philippines",
    capital: "마닐라",
    engCapital: "Manila",
    continent: "아시아",
    location: "동남아시아 태평양 연안의 섬나라",
    trivia: "7천여 개의 산호섬으로 구성된 아름다운 열대 국가로 세계적 휴양지인 보라카이와 세부 섬이 있습니다.",
    landmarks: ["보라카이 섬", "초콜릿 힐", "인트라무로스"]
  },
  {
    code: "id",
    name: "인도네시아",
    engName: "Indonesia",
    capital: "자카르타",
    engCapital: "Jakarta",
    continent: "아시아",
    location: "동남아시아 적도 부근에 위치",
    trivia: "1만 7천 개가 넘는 크고 작은 섬들로 이루어진 세계 최대 섬나라로 신비로운 발리 휴양지가 널리 이름났습니다.",
    landmarks: ["발리 섬", "보로부두르 사원", "브로모 화산"]
  },
  {
    code: "my",
    name: "말레이시아",
    engName: "Malaysia",
    capital: "쿠알라룸푸르",
    engCapital: "Kuala Lumpur",
    continent: "아시아",
    location: "동남아시아 말레이 반도에 위치",
    trivia: "말레이인, 중국인, 인도인이 화합하는 다민족 국가이며, 하늘을 찌를 듯 솟은 페트로나스 트윈 타워가 랜드마크입니다.",
    landmarks: ["페트로나스 트윈 타워", "바투 동굴", "키나발루 국립공원"]
  },
  {
    code: "sg",
    name: "싱가포르",
    engName: "Singapore",
    capital: "싱가포르",
    engCapital: "Singapore",
    continent: "아시아",
    location: "말레이 반도 남단 섬나라",
    trivia: "도시 전체가 정원처럼 가꿔진 아시아 금융/관광의 중심지로 사자 머리에 물고기 몸을 한 머라이언이 상징입니다.",
    landmarks: ["마리나 베이 샌즈", "가든스 바이 더 베이", "센토사 섬"]
  },
  {
    code: "sa",
    name: "사우디아라비아",
    engName: "Saudi Arabia",
    capital: "리야드",
    engCapital: "Riyadh",
    continent: "아시아",
    location: "중동 아라비아 반도에 위치",
    trivia: "넓은 모래 사막과 함께 막대한 석유가 매장된 중동의 맹주이며, 이슬람교의 최고 성지 메카가 있습니다.",
    landmarks: ["메카 대사원", "마다인 살레 유적", "킹덤 센터 타워"]
  },
  {
    code: "ae",
    name: "아랍에미리트",
    engName: "United Arab Emirates",
    capital: "아부다비",
    engCapital: "Abu Dhabi",
    continent: "아시아",
    location: "아라비아 반도 동남부에 위치",
    trivia: "7개의 토후국이 뭉친 연합 국가로, 세계에서 가장 높은 빌딩 부르즈 할리파가 위치한 두바이가 유명합니다.",
    landmarks: ["부르즈 할리파", "팜 주메이라 인공섬", "셰이크 자이드 그랜드 모스크"]
  },
  {
    code: "tr",
    name: "튀르키예",
    engName: "Turkey",
    capital: "앙카라",
    engCapital: "Ankara",
    continent: "아시아",
    location: "아시아와 유럽 대륙 사이에 위치",
    trivia: "형제의 나라로 불리며, 카파도키아의 열기구 관광과 기독교/이슬람 유산이 융합된 성 소피아 성당이 유명합니다.",
    landmarks: ["성 소피아 성당", "카파도키아 괴레메", "파묵칼레 석회화"]
  },
  {
    code: "il",
    name: "이스라엘",
    engName: "Israel",
    capital: "예루살렘",
    engCapital: "Jerusalem",
    continent: "아시아",
    location: "중동 지중해 연안에 위치",
    trivia: "기독교, 이슬람교, 유대교의 공통 성지인 예루살렘을 두고 있으며 염분이 매우 높아 몸이 둥둥 뜨는 사해가 유명합니다.",
    landmarks: ["예루살렘 통곡의 벽", "사해 호수", "텔아비브 해변"]
  },
  // [나머지 46개국]
  {
    code: "mn",
    name: "몽골",
    engName: "Mongolia",
    capital: "울란바토르",
    engCapital: "Ulaanbaatar",
    continent: "아시아",
    location: "아시아 동부 내륙에 위치",
    trivia: "끝없는 초원과 고비 사막이 있으며, 조립식 둥근 텐트인 전통 가옥 게르를 지어 유목 생활을 하는 나라입니다.",
    landmarks: ["고비 사막", "테를지 국립공원"]
  },
  {
    code: "af",
    name: "아프가니스탄",
    engName: "Afghanistan",
    capital: "카불",
    engCapital: "Kabul",
    continent: "아시아",
    location: "중앙아시아 남부에 위치",
    trivia: "높고 험난한 힌두쿠시 산맥이 가로지르며 동양과 서양을 잇는 오래된 실크로드 교역의 중심지였습니다.",
    landmarks: ["바미안 석굴 유적", "바부르 정원"]
  },
  {
    code: "am",
    name: "아르메니아",
    engName: "Armenia",
    capital: "예레반",
    engCapital: "Yerevan",
    continent: "아시아",
    location: "서아시아 코카서스 지역에 위치",
    trivia: "세계 최초로 기독교를 국교로 선언한 국가로, 험준한 산악 지대 속에 수천 년 된 유서 깊은 성당들이 보존되어 있습니다.",
    landmarks: ["게하르트 수도원", "타테브 수도원"]
  },
  {
    code: "az",
    name: "아제르바이잔",
    engName: "Azerbaijan",
    capital: "바쿠",
    engCapital: "Baku",
    continent: "아시아",
    location: "코카서스 카스피해 연안에 위치",
    trivia: "불의 나라로 불리며, 땅에서 천연가스가 불타오르는 독특한 지형과 카스피해 연안 석유 수출로 부유합니다.",
    landmarks: ["플레임 타워", "고부스탄 암각화"]
  },
  {
    code: "bd",
    name: "방글라데시",
    engName: "Bangladesh",
    capital: "다카",
    engCapital: "Dhaka",
    continent: "아시아",
    location: "인도 인도양 연안에 위치",
    trivia: "벵골만을 끼고 갠지스강 델타 평야에 위치하여 쌀농사가 매우 잘 되고 세계 최장 해변과 망그로브 숲이 있습니다.",
    landmarks: ["콕스바자르 최장 해변", "순다르반스 망그로브 숲"]
  },
  {
    code: "bn",
    name: "브루나이",
    engName: "Brunei",
    capital: "반다르스리브가완",
    engCapital: "Bandar Seri Begawan",
    continent: "아시아",
    location: "보르네오섬 북부에 위치",
    trivia: "석유와 천연가스 생산국으로 부유한 동남아시아의 왕정 국가이며 황금으로 장식된 호화로운 모스크가 자랑거리입니다.",
    landmarks: ["오마르 알리 사이푸딘 모스크", "캄퐁 아이에 수상가옥"]
  },
  {
    code: "bt",
    name: "부탄",
    engName: "Bhutan",
    capital: "팀부",
    engCapital: "Thimphu",
    continent: "아시아",
    location: "히말라야 산맥 동부에 위치",
    trivia: "은둔의 왕국으로 불리며 국민 총행복 지수를 중시하고 때 묻지 않은 대자연 속에 불교 전통을 잇는 나라입니다.",
    landmarks: ["탁상 사원 (호랑이 둥지)", "푸나카 종 성채"]
  },
  {
    code: "cy",
    name: "키프로스",
    engName: "Cyprus",
    capital: "니코시아",
    engCapital: "Nicosia",
    continent: "아시아",
    location: "지중해 동부의 섬나라",
    trivia: "그리스계와 튀르키예계가 남북으로 갈려 있으나 고대 그리스 로마 유적과 아름다운 지중해 해변이 가득합니다.",
    landmarks: ["파포스 고대유적지", "아프로디테 바위"]
  },
  {
    code: "ge",
    name: "조지아",
    engName: "Georgia",
    capital: "트빌리시",
    engCapital: "Tbilisi",
    continent: "아시아",
    location: "코카서스 산맥 남쪽에 위치",
    trivia: "인류 최초의 와인 발상지 중 하나로 험준한 산맥 속 고풍스러운 교회들과 조지아 와인이 유명합니다.",
    landmarks: ["카즈베기 게르기티 교회", "바르지아 동굴도시"]
  },
  {
    code: "iq",
    name: "이라크",
    engName: "Iraq",
    capital: "바그다드",
    engCapital: "Baghdad",
    continent: "아시아",
    location: "중동 메소포타미아 평원에 위치",
    trivia: "인류 4대 문명 중 하나인 메소포타미아 문명과 고대 바빌론 제국의 찬란한 유산을 품은 나라입니다.",
    landmarks: ["바빌론 유적", "알 아스카리 모스크"]
  },
  {
    code: "ir",
    name: "이란",
    engName: "Iran",
    capital: "테헤란",
    engCapital: "Tehran",
    continent: "아시아",
    location: "중동 이란 고원에 위치",
    trivia: "찬란했던 고대 페르시아 제국의 후예로 전통 카펫과 정교하고 화려한 모스크 유적이 잘 보존되어 있습니다.",
    landmarks: ["페르세폴리스 궁전유적", "이스파한 나크셰 자한 광장"]
  },
  {
    code: "jo",
    name: "요르단",
    engName: "Jordan",
    capital: "암만",
    engCapital: "Amman",
    continent: "아시아",
    location: "중동 아라비아 사막 북서쪽에 위치",
    trivia: "붉은 바위 절벽을 깎아 만든 고대 비밀 요새 페트라와 아름다운 사막 와디럼이 전 세계 여행자들을 매료시킵니다.",
    landmarks: ["페트라 유적지", "와디럼 붉은 사막", "로마 원형극장"]
  },
  {
    code: "kg",
    name: "키르기스스탄",
    engName: "Kyrgyzstan",
    capital: "비슈케크",
    engCapital: "Bishkek",
    continent: "아시아",
    location: "중앙아시아 톈산산맥 자락에 위치",
    trivia: "국토의 대부분이 눈 덮인 거대한 산악 지대로 '중앙아시아의 스위스'라 불리며 맑고 푸른 이식쿨 호수가 자랑입니다.",
    landmarks: ["이식쿨 호수", "알라아르차 국립공원"]
  },
  {
    code: "kh",
    name: "캄보디아",
    engName: "Cambodia",
    capital: "프놈펜",
    engCapital: "Phnom Penh",
    continent: "아시아",
    location: "인도차이나 반도 남서부에 위치",
    trivia: "밀림 속에 숨겨져 있던 크메르 제국의 찬란한 신전 유적인 앙코르와트가 있는 전 세계적인 문화유산 국가입니다.",
    landmarks: ["앙코르와트 사원", "톤레삽 대호수", "바이온 사원"]
  },
  {
    code: "kp",
    name: "북한",
    engName: "North Korea",
    capital: "평양",
    engCapital: "Pyongyang",
    continent: "아시아",
    location: "아시아 동부 한반도 북부에 위치",
    trivia: "대한민국과 휴전선을 사이에 두고 대치 중인 분단 국가로 민족의 명산 백두산과 묘향산 등이 있습니다.",
    landmarks: ["백두산", "금강산", "주체사상탑"]
  },
  {
    code: "kw",
    name: "쿠웨이트",
    engName: "Kuwait",
    capital: "쿠웨이트시티",
    engCapital: "Kuwait City",
    continent: "아시아",
    location: "페르시아만 연안 중동 국가",
    trivia: "석유 자원이 매우 부유하며 미래지향적 형태의 건축물인 쿠웨이트 타워가 랜드마크인 사막 국가입니다.",
    landmarks: ["쿠웨이트 타워", "그랜드 모스크"]
  },
  {
    code: "kz",
    name: "카자흐스탄",
    engName: "Kazakhstan",
    capital: "아스타나",
    engCapital: "Astana",
    continent: "아시아",
    location: "중앙아시아 내륙에 위치",
    trivia: "세계 최대 크기의 영토를 가진 내륙국이며 넓은 스텝 평원과 급속도로 발전한 미래 도시 아스타나가 있습니다.",
    landmarks: ["바이테렉 타워", "차린 캐년 계곡"]
  },
  {
    code: "la",
    name: "라오스",
    engName: "Laos",
    capital: "비엔티안",
    engCapital: "Vientiane",
    continent: "아시아",
    location: "인도차이나 반도 내륙에 위치",
    trivia: "동남아 유일의 내륙국으로 고풍스러운 사원과 방비엥의 아름다운 카르스트 산수 및 석회암 동굴이 유명합니다.",
    landmarks: ["탓 루앙 황금사원", "방비엥 블루라군"]
  },
  {
    code: "lb",
    name: "레바논",
    engName: "Lebanon",
    capital: "베이루트",
    engCapital: "Beirut",
    continent: "아시아",
    location: "중동 지중해 동쪽 연안에 위치",
    trivia: "중동에서 기독교와 이슬람이 융합된 독특한 문화를 가졌으며 향기로운 중동 백향목(시더)의 발상지입니다.",
    landmarks: ["바알베크 로마유적", "제이타 석회동굴"]
  },
  {
    code: "lk",
    name: "스리랑카",
    engName: "Sri Lanka",
    capital: "스리자야와르데네푸라코테",
    engCapital: "Sri Jayawardenepura Kotte",
    continent: "아시아",
    location: "인도 남부 인도양의 섬나라",
    trivia: "차(Tea) 생산으로 널리 알려진 불교 문화의 거점으로 숲속 깎아지른 절벽 성채인 시기리야가 유명합니다.",
    landmarks: ["시기리야 바위성채", "덴불라 황금사원"]
  },
  {
    code: "mm",
    name: "미얀마",
    engName: "Myanmar",
    capital: "네피도",
    engCapital: "Naypyidaw",
    continent: "아시아",
    location: "인도차이나 반도 서부에 위치",
    trivia: "금빛 불탑의 나라이며 수천 개의 붉은 벽돌 불교 유적이 지평선을 수놓는 바간 유적지가 널리 이름났습니다.",
    landmarks: ["쉐다곤 파고다", "바간 불탑 사원군"]
  },
  {
    code: "mv",
    name: "몰디브",
    engName: "Maldives",
    capital: "말레",
    engCapital: "Male",
    continent: "아시아",
    location: "인도 남서쪽 인도양의 섬나라",
    trivia: "1천 개가 넘는 에메랄드 산호섬으로 구성된 아름다운 해양 관광지로 신혼여행지로 전 세계적 사랑을 받습니다.",
    landmarks: ["말레 수산시장", "리조트 수상가옥"]
  },
  {
    code: "np",
    name: "네팔",
    engName: "Nepal",
    capital: "카트만두",
    engCapital: "Kathmandu",
    continent: "아시아",
    location: "히말라야 산맥 중앙에 위치",
    trivia: "세계 최고봉인 에베레스트산을 품고 있어 전 세계 산악인들의 성지이며, 불교의 석가모니가 탄생한 나라입니다.",
    landmarks: ["에베레스트산", "스와얌부나트 사원 (원숭이 사원)"]
  },
  {
    code: "om",
    name: "오만",
    engName: "Oman",
    capital: "무스카트",
    engCapital: "Muscat",
    continent: "아시아",
    location: "아라비아 반도 동남단에 위치",
    trivia: "전통 아랍 고풍 문화를 가장 잘 간직한 친환경 국가로 웅장한 술탄 모스크와 깊은 계곡 와디들이 숨어 있습니다.",
    landmarks: ["술탄 카부스 그랜드 모스크", "와디 샤브 계곡"]
  },
  {
    code: "ps",
    name: "팔레스타인",
    engName: "Palestine",
    capital: "라말라",
    engCapital: "Ramallah",
    continent: "아시아",
    location: "중동 지중해 동부 연안에 위치",
    trivia: "요르단강 서안 지구와 가자 지구로 나뉘며 예수 탄생지인 베들레헴 등 성경 속 주요 장소들이 가득합니다.",
    landmarks: ["예수 탄생 교회 (베들레헴)", "예루살렘 바위의 돔"]
  },
  {
    code: "qa",
    name: "카타르",
    engName: "Qatar",
    capital: "도하",
    engCapital: "Doha",
    continent: "아시아",
    location: "아라비아 반도 동부 돌출 지역",
    trivia: "국민 1인당 소득이 세계 최고 수준인 매우 부유한 가스/석유 생산국으로 2022년 월드컵 개최지이기도 합니다.",
    landmarks: ["이슬람 예술 박물관", "수크 와키프 전통시장"]
  },
  {
    code: "sy",
    name: "시리아",
    engName: "Syria",
    capital: "다마스쿠스",
    engCapital: "Damascus",
    continent: "아시아",
    location: "중동 동부 지중해 연안에 위치",
    trivia: "인류 역사상 가장 오래 지속해서 거주해 온 수도 다마스쿠스를 가졌으나 아쉽게도 오랜 내전을 겪었습니다.",
    landmarks: ["우마이야 모스크", "팔미라 오아시스 도시 유적"]
  },
  {
    code: "tj",
    name: "타지키스탄",
    engName: "Tajikistan",
    capital: "두샨베",
    engCapital: "Dushanbe",
    continent: "아시아",
    location: "중앙아시아 파미르 고원에 위치",
    trivia: "세계의 지붕이라 불리는 험준한 파미르 고원이 국토의 대부분을 차지하여 대자연 비경이 펼쳐지는 곳입니다.",
    landmarks: ["파미르 하이웨이", "두샨베 깃대 공원"]
  },
  {
    code: "tl",
    name: "동티모르",
    engName: "East Timor",
    capital: "딜리",
    engCapital: "Dili",
    continent: "아시아",
    location: "인도네시아 동부 티모르섬에 위치",
    trivia: "21세기 최초의 독립 국가 중 하나로 훼손되지 않은 오염 없는 청정 바다 산호초와 부드러운 커피가 자랑입니다.",
    landmarks: ["딜리 크리스토 레이 구원자상", "아타우로 섬"]
  },
  {
    code: "tm",
    name: "투르크메니스탄",
    engName: "Turkmenistan",
    capital: "아시가바트",
    engCapital: "Ashgabat",
    continent: "아시아",
    location: "중앙아시아 이란 북쪽에 위치",
    trivia: "사막 한가운데 수십 년째 꺼지지 않고 가스가 불타오르는 '지옥의 문(다르바자 크레이터)'이 명물입니다.",
    landmarks: ["다르바자 가스 분화구 (지옥의 문)", "대리석 도시 아시가바트"]
  },
  {
    code: "tw",
    name: "대만",
    engName: "Taiwan",
    capital: "타이베이",
    engCapital: "Taipei",
    continent: "아시아",
    location: "아시아 동부 태평양의 섬나라",
    trivia: "세계적인 반도체 산업 강국이자 타이베이 101 빌딩, 지우펀의 야경 등 아기자기한 식도락 여행지로 인기 있습니다.",
    landmarks: ["타이베이 101 빌딩", "국립고궁박물원", "타이루거 협곡"]
  },
  {
    code: "uz",
    name: "우즈베키스탄",
    engName: "Uzbekistan",
    capital: "타슈켄트",
    engCapital: "Tashkent",
    continent: "아시아",
    location: "중앙아시아 실크로드 교차로에 위치",
    trivia: "과거 동서양 무역의 중심지로 푸른 돔과 화려한 푸른 타일로 지어진 이슬람 신학교들이 잘 보존되어 있습니다.",
    landmarks: ["사마르칸트 레기스탄 광장", "부하라 칼리얀 미나레트"]
  },
  {
    code: "ye",
    name: "예멘",
    engName: "Yemen",
    capital: "사나",
    engCapital: "Sana'a",
    continent: "아시아",
    location: "아라비아 반도 남단에 위치",
    trivia: "진흙 벽돌을 겹겹이 쌓아 올려 만든 세계 최초의 수직 아파트형 주택들이 사나 구시가지에 밀집해 신비롭습니다.",
    landmarks: ["사나 올드타운 점토 아파트", "소코트라 용혈수 섬"]
  },
  {
    code: "pk",
    name: "파키스탄",
    engName: "Pakistan",
    capital: "이슬라마바드",
    engCapital: "Islamabad",
    continent: "아시아",
    location: "인도 서북쪽 남부 아시아에 위치",
    trivia: "인류 고대 인더스 문명의 발상지이며, 세계에서 두 번째로 높은 산인 K2 산이 북부 산악지대에 우뚝 솟아 있습니다.",
    landmarks: ["K2 산", "바드샤히 모스크", "라호르 성채"]
  },
  {
    code: "bh",
    name: "바레인",
    engName: "Bahrain",
    capital: "마나마",
    engCapital: "Manama",
    continent: "아시아",
    location: "페르시아만 서부 사막의 섬나라",
    trivia: "사우디와 다리로 연결된 중동의 작은 섬나라로, 황량한 사막 한가운데 신비하게 살아가는 400년 된 생명의 나무가 있습니다.",
    landmarks: ["바레인 요새", "생명의 나무", "알 파테 그랜드 모스크"]
  },
  {
    code: "hk",
    name: "홍콩",
    engName: "Hong Kong",
    capital: "홍콩",
    engCapital: "Hong Kong",
    continent: "아시아",
    location: "중국 남부 광둥성 연안에 위치",
    trivia: "빅토리아 피크에서 내려다보는 고층 빌딩 숲과 화려한 밤거리의 레이저 쇼인 '심포니 오브 라이트'가 유명한 특별행정구입니다.",
    landmarks: ["빅토리아 피크", "침사추이 프롬나드", "디즈니랜드"]
  },
  {
    code: "mo",
    name: "마카오",
    engName: "Macau",
    capital: "마카오",
    engCapital: "Macau",
    continent: "아시아",
    location: "중국 남동부 연안의 도시지역",
    trivia: "포르투갈의 오랜 지배를 받아 유럽 풍의 성당 유적과 동양 문화가 결합되었으며 세계적인 대형 카지노 단지들이 많습니다.",
    landmarks: ["성 바울 성당 유적", "세나도 광장", "마카오 타워"]
  },
  {
    code: "nc",
    name: "북키프로스",
    engName: "Northern Cyprus",
    capital: "북니코시아",
    engCapital: "North Nicosia",
    continent: "아시아",
    location: "지중해 동부 키프로스섬 북부에 위치",
    trivia: "튀르키예인들이 거주하는 키프로스 섬 북쪽의 실질적 공화국으로 아름다운 성채 도시 기레네 성이 랜드마크입니다.",
    landmarks: ["벨라파이스 수도원", "기레네 성채 항구"]
  },
  {
    code: "ab",
    name: "압하스",
    engName: "Abkhazia",
    capital: "수후미",
    engCapital: "Sukhumi",
    continent: "아시아",
    location: "흑해 동부 코카서스 지역에 위치",
    trivia: "조지아 내에 위치하며 실질적인 자치 국가로 행사하는 흑해 연안의 아름다운 휴양지 겸 협곡 지대입니다.",
    landmarks: ["리사 호수", "수후미 해안식물원"]
  },
  {
    code: "so",
    name: "남오세티야",
    engName: "South Ossetia",
    capital: "츠힌발리",
    engCapital: "Tskhinvali",
    continent: "아시아",
    location: "코카서스 산맥 고산 지대에 위치",
    trivia: "조지아 북부 코카서스 산악 지대에 위치하며, 러시아와 국경을 접하고 독특한 고산 문화가 발달한 미승인 국가입니다.",
    landmarks: ["츠힌발리 국립박물관", "코카서스 최고산 봉우리"]
  },
  {
    code: "gu",
    name: "괌",
    engName: "Guam",
    capital: "하가냐",
    engCapital: "Hagatna",
    continent: "아시아",
    location: "서태평양 미크로네시아 제도에 위치",
    trivia: "미국의 자치 영토이나 아시아 관광객들이 많이 찾는 관광 허브로 에메랄드빛 해변인 투몬 베이가 자랑입니다.",
    landmarks: ["사랑의 절벽", "투몬 베이 해변", "라테스톤 공원"]
  },
  {
    code: "cc",
    name: "코코스 제도",
    engName: "Cocos Islands",
    capital: "웨스트 아일랜드",
    engCapital: "West Island",
    continent: "아시아",
    location: "인도양 동부 오스트레일리아령 섬들",
    trivia: "찰스 다윈이 환초 이론을 연구한 곳으로 아름다운 산호초와 푸른 열대 야자수 바다가 사람들의 발길을 이끕니다.",
    landmarks: ["코스 해변", "웨스트 아일랜드 코코야자숲"]
  },
  {
    code: "cx",
    name: "크리스마스 섬",
    engName: "Christmas Island",
    capital: "플라잉피시코브",
    engCapital: "Flying Fish Cove",
    continent: "아시아",
    location: "인도양 동부 호주령 화산섬",
    trivia: "우기가 되면 숲속에서 바닷가로 수천만 마리의 붉은 게들이 일제히 산란하러 이동하는 신비한 붉은 게 대이동이 일어납니다.",
    landmarks: ["붉은게 이동 통로 국립공원", "더 블로우홀 해안"]
  },
  {
    code: "io",
    name: "영국령 인도양 영토",
    engName: "British Indian Ocean Territory",
    capital: "디에고가르시아",
    engCapital: "Diego Garcia",
    continent: "아시아",
    location: "인도양 한가운데 위치한 환초섬들",
    trivia: "미군과 영국군의 군사기지가 있는 디에고가르시아 섬을 중심으로 하며, 일반인 출입이 통제되는 자연 청정 지역입니다.",
    landmarks: ["디에고가르시아 군사기지 환초", "인도양 산호초해역"]
  },
  {
    code: "kd",
    name: "쿠르디스탄",
    engName: "Kurdistan",
    capital: "아르빌",
    engCapital: "Erbil",
    continent: "아시아",
    location: "이라크 북부 쿠르드 자치지역",
    trivia: "나라 없는 세계 최대 소수민족인 쿠르드족의 자치 지역으로 고대 흙벽돌 성채 유적인 아르빌 시타델이 유명합니다.",
    landmarks: ["아르빌 시타델 요새성채", "사미 압둘라만 공원"]
  },
  {
    code: "ru",
    name: "시베리아",
    engName: "Siberia",
    capital: "노보시비르스크",
    engCapital: "Novosibirsk",
    continent: "아시아",
    location: "아시아 북부 러시아 영토",
    trivia: "매우 춥고 울창한 타이가 침엽수림 지대이며, 세계에서 가장 깊은 민물고기 호수인 바이칼 호수를 품고 있습니다.",
    landmarks: ["바이칼 호수", "노보시비르스크 오페라 극장"]
  },

  // ==========================================
  // --- 유럽 (Europe) - 총 50개국 ---
  // ==========================================
  // [주요국 15개국 선두 배치]
  {
    code: "gb",
    name: "영국",
    engName: "United Kingdom",
    capital: "런던",
    engCapital: "London",
    continent: "유럽",
    location: "유럽 서북부 대서양의 섬나라",
    trivia: "과거 세계 산업혁명의 발상지이자 웅장한 시계탑 빅벤과 전통 왕실 근위병 교대식으로 상징되는 문화 강국입니다.",
    landmarks: ["빅벤 & 런던아이", "버킹엄 궁전", "스톤헨지 거석"]
  },
  {
    code: "fr",
    name: "프랑스",
    engName: "France",
    capital: "파리",
    engCapital: "Paris",
    continent: "유럽",
    location: "유럽 서부에 위치",
    trivia: "세계 패션과 예술, 미식의 상징적인 중심 국가로 세느강변에 높이 솟아오른 철골 에펠탑이 대표 랜드마크입니다.",
    landmarks: ["에펠탑", "루브르 박물관", "베르사유 궁전"]
  },
  {
    code: "de",
    name: "독일",
    engName: "Germany",
    capital: "베를린",
    engCapital: "Berlin",
    continent: "유럽",
    location: "중부 유럽에 위치",
    trivia: "아름다운 라인강과 웅장한 고성, 정밀한 기계 및 자동차 산업이 발달했고 세계 최대 맥주 축제 옥토버페스트가 열립니다.",
    landmarks: ["브란덴부르크 문", "노이슈반스타인 성", "쾰른 대성당"]
  },
  {
    code: "it",
    name: "이탈리아",
    engName: "Italy",
    capital: "로마",
    engCapital: "Rome",
    continent: "유럽",
    location: "유럽 남부 장화 모양 반도",
    trivia: "고대 거대한 로마 제국의 중심지로 원형 경기장 콜로세움과 피자의 본고장이며 유서 깊은 유적들이 즐비합니다.",
    landmarks: ["콜로세움", "피사의 사탑", "베네치아 대운하"]
  },
  {
    code: "es",
    name: "스페인",
    engName: "Spain",
    capital: "마드리드",
    engCapital: "Madrid",
    continent: "유럽",
    location: "유럽 남서부 이베리아 반도에 위치",
    trivia: "화려한 가우디의 예술적인 성가족 성당과 열정적인 춤 플라멩코, 투우 경기 및 맛있는 타파스가 대표적입니다.",
    landmarks: ["사그라다 파밀리아 성당", "알함브라 궁전", "구엘 공원"]
  },
  {
    code: "ru",
    name: "러시아",
    engName: "Russia",
    capital: "모스크바",
    engCapital: "Moscow",
    continent: "유럽",
    location: "유럽 동부에서 아시아 북부에 위치",
    trivia: "세계에서 영토 면적이 가장 큰 나라이며 붉은 광장에 알록달록 양파 모양 지붕을 한 바실리 성당이 상징입니다.",
    landmarks: ["붉은 광장 & 크렘린 궁전", "성 바실리 성당", "에르미타주 미술관"]
  },
  {
    code: "gr",
    name: "그리스",
    engName: "Greece",
    capital: "아테네",
    engCapital: "Athens",
    continent: "유럽",
    location: "유럽 남부 발칸반도 남단에 위치",
    trivia: "고대 올림픽과 서양 문명의 시작이며 산 정상에 우뚝 선 파르테논 신전과 파란 지붕의 산토리니 섬이 대표적입니다.",
    landmarks: ["파르테논 신전", "산토리니 섬", "메테오라 절벽수도원"]
  },
  {
    code: "ch",
    name: "스위스",
    engName: "Switzerland",
    capital: "베른",
    engCapital: "Bern",
    continent: "유럽",
    location: "유럽 중부 알프스산맥에 위치",
    trivia: "아름다운 만년설의 알프스 마테호른 영봉과 맑은 호수가 빛나며 맛있는 치즈 퐁뒤와 정밀한 시계가 대표적입니다.",
    landmarks: ["융프라우요흐", "마테호른 영봉", "루체른 카펠교"]
  },
  {
    code: "nl",
    name: "네덜란드",
    engName: "Netherlands",
    capital: "암스테르담",
    engCapital: "Amsterdam",
    continent: "유럽",
    location: "유럽 서북부 저지대에 위치",
    trivia: "바다보다 낮은 영토를 극복하기 위한 풍차 유적과 형형색색의 튤립 정원, 운하와 자전거가 가득한 환경 도시입니다.",
    landmarks: ["킨더다이크 풍차마을", "큐켄호프 튤립공원", "암스테르담 운하"]
  },
  {
    code: "be",
    name: "벨기에",
    engName: "Belgium",
    capital: "브뤼셀",
    engCapital: "Brussels",
    continent: "유럽",
    location: "유럽 서부 북해 연안에 위치",
    trivia: "유럽연합(EU) 본부가 있으며 달콤한 와플과 수제 초콜릿, 귀여운 오줌싸개 동상이 도심의 상징물입니다.",
    landmarks: ["그랑 플라스 광장", "오줌싸개 동상", "아토미움"]
  },
  {
    code: "se",
    name: "스웨덴",
    engName: "Sweden",
    capital: "스톡홀름",
    engCapital: "Stockholm",
    continent: "유럽",
    location: "스칸디나비아 반도 동부에 위치",
    trivia: "조립식 가구 이케아와 전설적 그룹 아바의 고향이자 노벨상이 수여되는 세련된 친환경 복지 국가입니다.",
    landmarks: ["스톡홀름 시청사", "바사박물관", "감라스탄 구시가지"]
  },
  {
    code: "no",
    name: "노르웨이",
    engName: "Norway",
    capital: "오슬로",
    engCapital: "Oslo",
    continent: "유럽",
    location: "스칸디나비아 반도 서부에 위치",
    trivia: "빙하가 깎아 만든 깊고 웅장한 피오르 만과 겨울철 밤하늘을 수놓는 신비로운 오로라가 일품인 나라입니다.",
    landmarks: ["게이랑에르 피오르", "오슬로 비겔란 조각공원", "로포텐 제도"]
  },
  {
    code: "fi",
    name: "핀란드",
    engName: "Finland",
    capital: "헬싱키",
    engCapital: "Helsinki",
    continent: "유럽",
    location: "유럽 북부 발트해 연안에 위치",
    trivia: "산타클로스의 고향 마을이 있는 숲과 호수의 나라이며 뜨거운 자작나무 사우나와 캐릭터 무민이 탄생했습니다.",
    landmarks: ["산타클로스 마을 (로바니에미)", "수오멘린나 요새", "템펠리아우키오 교회"]
  },
  {
    code: "at",
    name: "오스트리아",
    engName: "Austria",
    capital: "빈",
    engCapital: "Vienna",
    continent: "유럽",
    location: "유럽 중부 알프스 동부에 위치",
    trivia: "음악가 모차르트와 베토벤이 활약한 클래식 음악의 고향이며 알프스 산속 예쁜 호수 마을 할슈타트가 아름답습니다.",
    landmarks: ["쇤브룬 궁전", "할슈타트 호수마을", "성 슈테판 대성당"]
  },
  {
    code: "pt",
    name: "포르투갈",
    engName: "Portugal",
    capital: "리스본",
    engCapital: "Lisbon",
    continent: "유럽",
    location: "이베리아 반도 서쪽 끝에 위치",
    trivia: "대항해시대 개척의 역사와 에그타르트, 구시가지를 가로지르는 노란색 전통 트램이 리스본의 대표적 비경입니다.",
    landmarks: ["벨렝탑", "페나 성 (신트라)", "제로나무스 수도원"]
  },
  // [나머지 35개국]
  {
    code: "al",
    name: "알바니아",
    engName: "Albania",
    capital: "티라나",
    engCapital: "Tirana",
    continent: "유럽",
    location: "발칸반도 남서쪽에 위치",
    trivia: "오랫동안 외부와 단절되었던 공산 국가였으나 때 묻지 않은 저렴하고 아름다운 아드리아해 해변이 보물입니다.",
    landmarks: ["베라트 천 개의 창문 도시", "부트린트 고대유적"]
  },
  {
    code: "ba",
    name: "보스니아 헤르체고비나",
    engName: "Bosnia and Herzegovina",
    capital: "사라예보",
    engCapital: "Sarajevo",
    continent: "유럽",
    location: "발칸반도 서부에 위치",
    trivia: "동양과 서양 종교 문화가 평화롭게 만나는 곳으로 폭격 후 재건된 평화의 다리 스타리 모스트가 상징입니다.",
    landmarks: ["모스타르 다리 (스타리 모스트)", "사라예보 바슈카르지아"]
  },
  {
    code: "bg",
    name: "불가리아",
    engName: "Bulgaria",
    capital: "소피아",
    engCapital: "Sofia",
    continent: "유럽",
    location: "발칸반도 동부에 위치",
    trivia: "건강한 유산균 요구르트와 세계 최대 생산량을 자랑하는 아름답고 향기로운 장미 계곡 축제가 상징입니다.",
    landmarks: ["릴라 수도원", "알렉산드르 넵스키 대성당"]
  },
  {
    code: "by",
    name: "벨라루스",
    engName: "Belarus",
    capital: "민스크",
    engCapital: "Minsk",
    continent: "유럽",
    location: "동유럽 평원 북서부에 위치",
    trivia: "동유럽에서 전통 슬라브 숲 문화를 고수하며 웅장하고 견고하게 보존된 미르 성이 대표적인 유산입니다.",
    landmarks: ["미르 성", "브레스트 요새"]
  },
  {
    code: "cz",
    name: "체코",
    engName: "Czech Republic",
    capital: "프라하",
    engCapital: "Prague",
    continent: "유럽",
    location: "중부 유럽에 위치",
    trivia: "프라하의 붉은 지붕과 카렐교, 고딕 성채와 맛있는 체코 맥주 필스너가 대표적인 매력물입니다.",
    landmarks: ["프라하 성", "카렐교", "천문시계탑"]
  },
  {
    code: "dk",
    name: "덴마크",
    engName: "Denmark",
    capital: "코펜하겐",
    engCapital: "Copenhagen",
    continent: "유럽",
    location: "유럽 유틀란트 반도에 위치",
    trivia: "안데르센 동화 인어공주 동상과 조립식 블록 완구 레고의 고향으로 행복 지수가 최고인 자전거 나라입니다.",
    landmarks: ["인어공주 동상", "뉘하운 운하거리", "티볼리 공원"]
  },
  {
    code: "ee",
    name: "에스토니아",
    engName: "Estonia",
    capital: "탈린",
    engCapital: "Tallinn",
    continent: "유럽",
    location: "발트해 동부 발트 3국 중 하나",
    trivia: "중세 성벽 도시 탈린 구시가지가 동화 속처럼 보존되어 있으며, IT 및 전자 정부 선진국으로 유명합니다.",
    landmarks: ["탈린 툼페아 언덕 구시가지", "알렉산드르 넵스키 성당"]
  },
  {
    code: "hr",
    name: "크로아티아",
    engName: "Croatia",
    capital: "자그레브",
    engCapital: "Zagreb",
    continent: "유럽",
    location: "지중해 아드리아해 연안에 위치",
    trivia: "아름다운 붉은 지붕 성벽 성채 도시 두브로브니크와 요정의 숲 플리트비체 호수 국립공원이 유명합니다.",
    landmarks: ["두브로브니크 성벽", "플리트비체 국립공원"]
  },
  {
    code: "hu",
    name: "헝가리",
    engName: "Hungary",
    capital: "부다페스트",
    engCapital: "Budapest",
    continent: "유럽",
    location: "중동부 유럽 다뉴브 평원에 위치",
    trivia: "부다페스트의 화려한 국회의사당 야경과 오랜 유황 온천 문화, 그리고 매콤한 파프리카 육개장 굴라시가 명물입니다.",
    landmarks: ["어부의 요새", "부다페스트 국회의사당", "세체니 온천"]
  },
  {
    code: "ie",
    name: "아일랜드",
    engName: "Ireland",
    capital: "더블린",
    engCapital: "Dublin",
    continent: "유럽",
    location: "영국 서쪽 대서양의 섬나라",
    trivia: "사면이 목초지라 '에메랄드 섬'이라 불리며 문학가들의 도시 더블린과 흑맥주 기네스가 사랑받는 나라입니다.",
    landmarks: ["모허 절벽", "트리니티 칼리지 도서관"]
  },
  {
    code: "is",
    name: "아이슬란드",
    engName: "Iceland",
    capital: "레이캬비크",
    engCapital: "Reykjavik",
    continent: "유럽",
    location: "북대서양 유럽 최북단의 섬나라",
    trivia: "화산의 뜨거운 열기와 빙하의 차가움이 공존하는 '얼음과 불의 땅'으로 온천 블루라군이 신비롭습니다.",
    landmarks: ["블루 라군 온천", "굴포스 폭포", "게이시르 간헐천"]
  },
  {
    code: "lt",
    name: "리투아니아",
    engName: "Lithuania",
    capital: "빌뉴스",
    engCapital: "Vilnius",
    continent: "유럽",
    location: "발트해 연안 발트 3국 중 하나",
    trivia: "중세 웅장했던 대공국의 역사 유산을 간직하였으며, 호수 위 동화 속 요새 같은 트라카이 성이 명물입니다.",
    landmarks: ["트라카이 호수성채", "십자가의 언덕"]
  },
  {
    code: "lu",
    name: "룩셈부르크",
    engName: "Luxembourg",
    capital: "룩셈부르크",
    engCapital: "Luxembourg",
    continent: "유럽",
    location: "프랑스와 독일, 벨기에 사이에 위치",
    trivia: "국토의 대부분이 요새화된 절벽과 숲으로 둘러싸여 있으며 세계 최고 수준의 고소득 금융 소국입니다.",
    landmarks: ["아돌프 다리", "보크 포대 절벽요새"]
  },
  {
    code: "lv",
    name: "라트비아",
    engName: "Latvia",
    capital: "리가",
    engCapital: "Riga",
    continent: "유럽",
    location: "발트해 연안 발트 3국의 중심",
    trivia: "수도 리가는 중세 고딕 및 아르누보 건축물의 보물창고로 불리며, 발트해의 베네치아라는 별명이 있습니다.",
    landmarks: ["리가 검은머리전당", "룬달레 궁전"]
  },
  {
    code: "md",
    name: "몰도바",
    engName: "Moldova",
    capital: "키시너우",
    engCapital: "Chisinau",
    continent: "유럽",
    location: "루마니아와 우크라이나 사이에 위치",
    trivia: "세계적인 대규모 지하 와인 보관고와 성채 요새를 가졌으며 고품격 와인이 풍부하게 생산되는 동유럽 소국입니다.",
    landmarks: ["밀레스티 미치 지하와인고", "오르헤이 베키 절벽수도원"]
  },
  {
    code: "me",
    name: "몬테네그로",
    engName: "Montenegro",
    capital: "포드고리차",
    engCapital: "Podgorica",
    continent: "유럽",
    location: "발칸반도 아드리아해 연안에 위치",
    trivia: "검은 산이라는 국명답게 높은 협곡이 펼쳐지며 지중해 최고의 피오르 풍경인 코토르 만이 명소입니다.",
    landmarks: ["코토르 성곽도시 만", "타라 협곡다리"]
  },
  {
    code: "mk",
    name: "북마케도니아",
    engName: "North Macedonia",
    capital: "스코페",
    engCapital: "Skopye",
    continent: "유럽",
    location: "발칸반도 중앙 내륙에 위치",
    trivia: "고대 알렉산더 대왕의 상징과 유서 깊은 오흐리드 호수를 두었으며 도심에 화려한 대형 동상이 많습니다.",
    landmarks: ["오흐리드 맑은 호수", "스코페 로마 스톤 브릿지"]
  },
  {
    code: "mt",
    name: "몰타",
    engName: "Malta",
    capital: "발레타",
    engCapital: "Valletta",
    continent: "유럽",
    location: "지중해 이탈리아 남부 섬나라",
    trivia: "과거 요한 기사단 성채 요새 도시 발레타가 섬 전체에 고스란히 남아 있어 영화 촬영지로 각광받습니다.",
    landmarks: ["발레타 성벽 구도시", "블루 그로토 해상동굴"]
  },
  {
    code: "pl",
    name: "폴란드",
    engName: "Poland",
    capital: "바르샤바",
    engCapital: "Warsaw",
    continent: "유럽",
    location: "동유럽 평원 중앙에 위치",
    trivia: "과학자 퀴리 부인과 피아니스트 쇼팽의 고국이며 세계 최대 소금광산 바벨 성이 있는 역사 국가입니다.",
    landmarks: ["크라쿠프 바벨 성", "비엘리치카 지하소금광산"]
  },
  {
    code: "ro",
    name: "루마니아",
    engName: "Romania",
    capital: "부쿠레슈티",
    engCapital: "Bucharest",
    continent: "유럽",
    location: "동유럽 발칸반도 북부에 위치",
    trivia: "아름다운 카르파티아 산맥과 흡혈귀 드라큘라 소설의 모티브가 된 브란 성 요새가 우뚝 서 있습니다.",
    landmarks: ["브란 성 (드라큘라 성)", "펠레슈 궁전"]
  },
  {
    code: "rs",
    name: "세르비아",
    engName: "Serbia",
    capital: "베오그라드",
    engCapital: "Belgrade",
    continent: "유럽",
    location: "발칸반도 중앙 평원에 위치",
    trivia: "과학자 니콜라 테슬라의 조국이며 도나우강과 사바강이 만나는 아름다운 베오그라드 칼레메그단 요새가 훌륭합니다.",
    landmarks: ["베오그라드 요새성채", "성 사바 대성당"]
  },
  {
    code: "si",
    name: "슬로베니아",
    engName: "Slovenia",
    capital: "류블랴나",
    engCapital: "Ljubljana",
    continent: "유럽",
    location: "알프스 동단 지중해 근처에 위치",
    trivia: "그림 같은 절벽 성과 호수 한가운데 떠 있는 예쁜 성모 교회가 있는 블레드 호수가 신비롭습니다.",
    landmarks: ["블레드 호수 성모교회", "포스토이나 거대 석회동굴"]
  },
  {
    code: "sk",
    name: "슬로바키아",
    engName: "Slovakia",
    capital: "브라티슬라바",
    engCapital: "Bratislava",
    continent: "유럽",
    location: "중부 유럽 내륙 타트라산맥 근처",
    trivia: "웅장한 하이 타트라 산악 비경과 다뉴브 강변을 굽어보는 브라티슬라바 사각형 성채 요새가 대표적입니다.",
    landmarks: ["브라티슬라바 성", "하이 타트라 국립공원"]
  },
  {
    code: "ua",
    name: "우크라이나",
    engName: "Ukraine",
    capital: "키이우",
    engCapital: "Kyiv",
    continent: "유럽",
    location: "동유럽 흑해 연안 평원에 위치",
    trivia: "세계 최고의 밀 생산 흑토 지대를 가졌으며, 푸른색과 황금색의 정교하고 큰 정교회 성당들이 자랑입니다.",
    landmarks: ["키이우 페체르스크 수도원", "성 소피아 대성당"]
  },
  {
    code: "ad",
    name: "안도라",
    engName: "Andorra",
    capital: "안도라라벨랴",
    engCapital: "Andorra la Vella",
    continent: "유럽",
    location: "프랑스와 스페인 사이 피레네산맥",
    trivia: "피레네 산맥 꼭대기 고산 지대에 위치한 면세 관광 국가로 겨울철 스키와 쇼핑의 허브 도시입니다.",
    landmarks: ["카사 데 라 발 유적", "그랜드발리라 스키리조트"]
  },
  {
    code: "mc",
    name: "모나코",
    engName: "Monaco",
    capital: "모나코",
    engCapital: "Monaco",
    continent: "유럽",
    location: "프랑스 남동부 지중해 해안에 위치",
    trivia: "바티칸 다음으로 작은 미니 국가로 해안 요트 선착장, 카지노 몬테카를로와 F1 그랑프리가 유명합니다.",
    landmarks: ["몬테카를로 카지노", "모나코 대공궁", "해양학박물관"]
  },
  {
    code: "li",
    name: "리히텐슈타인",
    engName: "Liechtenstein",
    capital: "파두츠",
    engCapital: "Vaduz",
    continent: "유럽",
    location: "스위스와 오스트리아 사이 라인강변",
    trivia: "알프스 산속 요새 파두츠 성에 군주(공작)가 실제로 거주하며 정교한 특수 우표 발행으로 널리 알려졌습니다.",
    landmarks: ["파두츠 성채", "리히텐슈타인 미술관"]
  },
  {
    code: "sm",
    name: "산마리노",
    engName: "San Marino",
    capital: "산마리노",
    engCapital: "San Marino",
    continent: "유럽",
    location: "이탈리아 중북부 영토 내에 위치",
    trivia: "세계에서 가장 오래된 역사를 지닌 공화국으로, 티타노 산 절벽 꼭대기에 우뚝 솟은 요새 성채들이 환상적입니다.",
    landmarks: ["구아이타 요새 타워", "팔라초 푸블리코"]
  },
  {
    code: "va",
    name: "바티칸 시국",
    engName: "Vatican City",
    capital: "바티칸 시국",
    engCapital: "Vatican City",
    continent: "유럽",
    location: "이탈리아 로마 시내 내부에 위치",
    trivia: "교황이 다스리는 세계에서 가장 작은 독립국이자 카톨릭 신앙의 중심으로 거대한 성 베드로 대성당이 있습니다.",
    landmarks: ["성 베드로 대성당", "시스티나 성당 (천장화)", "바티칸 미술관"]
  },
  {
    code: "xk",
    name: "코소보",
    engName: "Kosovo",
    capital: "프리슈티나",
    engCapital: "Pristina",
    continent: "유럽",
    location: "발칸반도 중앙부 평원에 위치",
    trivia: "2008년 독립을 선언한 신생 독립국으로 오스만 제국과 비잔틴 종교 양식이 섞인 대리석 성당들이 있습니다.",
    landmarks: ["그라차니차 수도원", "프리슈티나 국립박물관"]
  },
  {
    code: "gi",
    name: "지브롤터",
    engName: "Gibraltar",
    capital: "지브롤터",
    engCapital: "Gibraltar",
    continent: "유럽",
    location: "스페인 남단 지중해 입구 영국령",
    trivia: "지중해와 대서양을 연결하는 입구의 전략적 요충지로 거대한 바위산과 서식하는 야생 원숭이가 명물입니다.",
    landmarks: ["지브롤터 거대 바위산", "성 마이클 동굴"]
  },
  {
    code: "fo",
    name: "페로 제도",
    engName: "Faroe Islands",
    capital: "토르스하운",
    engCapital: "Torshavn",
    continent: "유럽",
    location: "북대서양 영국과 아이슬란드 중간 섬들",
    trivia: "덴마크 자치령으로 깎아지른 해안 절벽 폭포와 지붕 위에 푸른 잔디를 심은 북유럽 전통 가옥이 독특합니다.",
    landmarks: ["물라포수르 절벽폭포", "팅가네스 목조지구"]
  },
  {
    code: "ax",
    name: "올란드 제도",
    engName: "Aland Islands",
    capital: "마리에함",
    engCapital: "Mariehamn",
    continent: "유럽",
    location: "스웨덴과 핀란드 사이 발트해 섬들",
    trivia: "핀란드 영토이나 스웨덴어를 쓰며 군대가 주둔하지 않는 비무장 자치 평화 지역으로 해양 낚시 요람입니다.",
    landmarks: ["카스텔홀름 성", "마리에함 선박박물관"]
  },
  {
    code: "sj",
    name: "스발바르 제도",
    engName: "Svalbard",
    capital: "롱위에아르뷔엔",
    engCapital: "Longyearbyen",
    continent: "유럽",
    location: "북극해 한가운데 위치한 노르웨이령",
    trivia: "사람보다 북극곰이 많이 사는 극지방으로 인류 최후의 날을 대비한 '글로벌 씨앗 저장고'가 깊은 터널 속에 숨어있습니다.",
    landmarks: ["스발바르 국제 씨앗저장고", "롱위에아르뷔엔 석탄광산구역"]
  },
  {
    code: "im",
    name: "맨 섬",
    engName: "Isle of Man",
    capital: "더블린",
    engCapital: "Douglas",
    continent: "유럽",
    location: "영국과 아일랜드 사이의 아이리시해",
    trivia: "영국 왕실 직속 자치 영토로, 꼬리가 전혀 없는 희귀 고양이 맨크스의 발상지이자 매년 오토바이 경주가 열립니다.",
    landmarks: ["필 성채요새", "락시 휠 거대물레방아"]
  },

  // ==========================================
  // --- 북아메리카 (North America) - 총 20개국 ---
  // ==========================================
  // [주요국 6개국 선두 배치]
  {
    code: "us",
    name: "미국",
    engName: "United States",
    capital: "워싱턴",
    engCapital: "Washington D.C.",
    continent: "북아메리카",
    location: "북아메리카 대륙 중앙에 위치",
    trivia: "자유의 여신상, 할리우드 영화 산업, IT 실리콘 밸리를 품은 거대한 영토의 세계 최강대국 중 하나입니다.",
    landmarks: ["자유의 여신상", "그랜드 캐니언", "타임스 스퀘어"]
  },
  {
    code: "ca",
    name: "캐나다",
    engName: "Canada",
    capital: "오타와",
    engCapital: "Ottawa",
    continent: "북아메리카",
    location: "북아메리카 대륙 북부에 위치",
    trivia: "세계에서 두 번째로 영토가 넓으며, 국기에 그려진 붉은 단풍잎(메이플 시럽)과 웅장한 로키산맥 자연이 자랑입니다.",
    landmarks: ["나이아가라 폭포", "밴프 국립공원 (로키)", "퀘벡 구시가지"]
  },
  {
    code: "mx",
    name: "멕시코",
    engName: "Mexico",
    capital: "멕시코시티",
    engCapital: "Mexico City",
    continent: "북아메리카",
    location: "북아메리카 대륙 남부에 위치",
    trivia: "고대 마야/아스테카 문명의 불가사의 피라미드가 남아있고 전통 매콤한 타코 요리와 모자 솜브레로가 특징입니다.",
    landmarks: ["치첸이차 마야피라미드", "테오티우아칸 해의 피라미드", "칸쿤 해변"]
  },
  {
    code: "cu",
    name: "쿠바",
    engName: "Cuba",
    capital: "아바나",
    engCapital: "Havana",
    continent: "북아메리카",
    location: "카리브해 서부의 섬나라",
    trivia: "카리브해의 붉은 열정 국가로 수도 아바나 거리를 누비는 1950년대식 파스텔톤 클래식 올드카와 시가가 명물입니다.",
    landmarks: ["아바나 구시가지 올드카", "비냘레스 계곡 (담배밭)"]
  },
  {
    code: "jm",
    name: "자메이카",
    engName: "Jamaica",
    capital: "킹스턴",
    engCapital: "Kingston",
    continent: "북아메리카",
    location: "카리브해 중앙의 섬나라",
    trivia: "레게 음악가 밥 말리와 번개 육상 선수 우사인 볼트의 고향이며 향이 감미로운 블루마운틴 커피가 생산됩니다.",
    landmarks: ["던즈 리버 폭포", "밥 말리 박물관"]
  },
  {
    code: "pa",
    name: "파나마",
    engName: "Panama",
    capital: "파나마시티",
    engCapital: "Panama City",
    continent: "북아메리카",
    location: "남북 아메리카를 잇는 운하 국가",
    trivia: "태평양과 대서양 바닷길을 통과시키는 거대 인공 운하 '파나마 운하' 덕에 해상 무역 교통의 요지입니다.",
    landmarks: ["파나마 운하 밀라플로레스 갑문", "카스코 비에호 구도심"]
  },
  // [나머지 14개국]
  {
    code: "bs",
    name: "바하마",
    engName: "Bahamas",
    capital: "나소",
    engCapital: "Nassau",
    continent: "북아메리카",
    location: "미국 플로리다 동쪽 카리브 섬나라",
    trivia: "수백 개의 에메랄드 산호섬으로 구성된 카리브해 천국으로 바다에서 헤엄치는 분홍 돼지 섬이 인기 명소입니다.",
    landmarks: ["빅마요네즈 돼지 해변", "아틀란티스 리조트"]
  },
  {
    code: "bz",
    name: "벨리즈",
    engName: "Belize",
    capital: "벨모판",
    engCapital: "Belmopan",
    continent: "북아메리카",
    location: "유카탄 반도 남동쪽에 위치",
    trivia: "지구의 푸른 눈이라 불리는 신비한 바닷속 거대 구멍인 '그레이트 블루홀'이 있는 다이버들의 낙원입니다.",
    landmarks: ["그레이트 블루홀", "랄마나이 마야유적"]
  },
  {
    code: "cr",
    name: "코스타리카",
    engName: "Costa Rica",
    capital: "산호세",
    engCapital: "San Jose",
    continent: "북아메리카",
    location: "중앙아메리카 협부의 친환경 국가",
    trivia: "국토의 25%가 국립공원으로 지정된 생태 천국으로, 울창한 우림 속 야생 나무늘보와 투칸 새가 많이 삽니다.",
    landmarks: ["아레날 활화산", "몬테베르데 안개숲"]
  },
  {
    code: "dm",
    name: "도미니카 연방",
    engName: "Dominica",
    capital: "로조",
    engCapital: "Roseau",
    continent: "북아메리카",
    location: "카리브해 소앤틸리스 제도의 섬나라",
    trivia: "자연 그대로의 화산 온천이 온 사방에서 뿜어져 나오며 땅 밑에서 펄펄 끓어오르는 보일링 호수가 있습니다.",
    landmarks: ["보일링 호수", "모른 트루아 피통 국립공원"]
  },
  {
    code: "do",
    name: "도미니카 공화국",
    engName: "Dominican Republic",
    capital: "산토도밍고",
    engCapital: "Santo Domingo",
    continent: "북아메리카",
    location: "카리브해 히스파니올라섬 동부",
    trivia: "신대륙을 발견한 콜롬부스의 시신 무덤이 안치되었으며, 아름다운 백사장 해변과 메렝게 음악 댄스가 유명합니다.",
    landmarks: ["산토도밍고 콜롬버스 궁전", "푼타카나 휴양해변"]
  },
  {
    code: "gd",
    name: "그레나다",
    engName: "Grenada",
    capital: "세인트조지스",
    engCapital: "St. George's",
    continent: "북아메리카",
    location: "카리브해 최남단의 섬나라",
    trivia: "향긋한 정향과 육두구(넛멕) 스파이스가 많이 생산되어 '향료의 섬'으로 불리며 알록달록 세인트조지스 항구가 예쁩니다.",
    landmarks: ["세인트조지스 파스텔 항구", "그랜드 안세 해변"]
  },
  {
    code: "gt",
    name: "과테말라",
    engName: "Guatemala",
    capital: "과테말라시티",
    engCapital: "Guatemala City",
    continent: "북아메리카",
    location: "중앙아메리카 유카탄 반도 남서부",
    trivia: "마야 문명의 최대 도시 유적인 티칼 국립공원과 화산재 흙에서 자라 깊은 초콜릿 향이 우러나는 커피가 맛있습니다.",
    landmarks: ["티칼 마야 문명 유적", "아티틀란 호수 (화산호)"]
  },
  {
    code: "hn",
    name: "온두라스",
    engName: "Honduras",
    capital: "테구시갈파",
    engCapital: "Tegucigalpa",
    continent: "북아메리카",
    location: "중앙아메리카 니카라과 북쪽에 위치",
    trivia: "마야 고대 상형문자가 적힌 거대 계단이 발굴된 코판 마야 유적과 카리브해의 때 묻지 않은 섬들이 있습니다.",
    landmarks: ["코판 마야 상형문자계단 유적", "로아탄 섬 산호초"]
  },
  {
    code: "ht",
    name: "아이티",
    engName: "Haiti",
    capital: "포르토프랭스",
    engCapital: "Port-au-Prince",
    continent: "북아메리카",
    location: "카리브해 히스파니올라섬 서부",
    trivia: "세계 최초로 흑인 노예들이 혁명을 일으켜 수립한 역사적 공화국으로 산꼭대기에 요새 시타델이 있습니다.",
    landmarks: ["시타델 라페리에르 요새", "상수시 궁전유적"]
  },
  {
    code: "ni",
    name: "니카라과",
    engName: "Nicaragua",
    capital: "마나구아",
    engCapital: "Managua",
    continent: "북아메리카",
    location: "중앙아메리카의 중심 호수국가",
    trivia: "상어가 살 만큼 거대한 민물 호수인 니카라과 호수가 있으며 호수 가운데 우뚝 솟은 두 개의 화산섬이 비경입니다.",
    landmarks: ["오메테페 섬 화산", "그라나다 스페인식 성당"]
  },
  {
    code: "pr",
    name: "푸에르토리코",
    engName: "Puerto Rico",
    capital: "산후안",
    engCapital: "San Juan",
    continent: "북아메리카",
    location: "카리브해 동부의 미국 자치령 섬",
    trivia: "미국의 자치령이나 라틴 풍이 강하며 옛 요새도시 산후안 요새와 밤하늘에 야광 벌레가 빛나는 바이오 루미네선트 베이가 유명합니다.",
    landmarks: ["엘 모로 요새성채", "모스키토 야광 베이"]
  },
  {
    code: "sv",
    name: "엘살바도르",
    engName: "El Salvador",
    capital: "산살바도르",
    engCapital: "San Salvador",
    continent: "북아메리카",
    location: "중앙아메리카 태평양 연안 국가",
    trivia: "중앙아메리카에서 가장 작은 영토를 가졌으나 태평양 서핑의 중심지이며 웅장한 활화산 산타아나가 있습니다.",
    landmarks: ["산타아나 활화산 분화구", "엘 툰코 서핑 해변"]
  },
  {
    code: "tt",
    name: "트리니다드 토바고",
    engName: "Trinidad and Tobago",
    capital: "포트오브스페인",
    engCapital: "Port of Spain",
    continent: "북아메리카",
    location: "남아메리카 베네수엘라 북쪽 카리브 섬나라",
    trivia: "드럼통을 깎아 만든 타악기인 스틸드럼 음악과 세계적인 길거리 카니발 축제가 카리브 해안을 흔드는 나라입니다.",
    landmarks: ["피치 레이크 자연 아스팔트 호수", "마라카스 해변"]
  },
  {
    code: "gl",
    name: "그린란드",
    engName: "Greenland",
    capital: "누크",
    engCapital: "Nuuk",
    continent: "북아메리카",
    location: "북대서양과 북극해 사이에 위치",
    trivia: "덴마크 영토의 자치령이자 세계에서 가장 큰 섬으로 국토의 80%가 두꺼운 얼음빙하와 일루리삿 피오르가 채우고 있습니다.",
    landmarks: ["일루리삿 아이스 피오르 빙하", "누크 국립박물관"]
  },

  // ==========================================
  // --- 남아메리카 (South America) - 총 15개국 ---
  // ==========================================
  // [주요국 6개국 선두 배치]
  {
    code: "br",
    name: "브라질",
    engName: "Brazil",
    capital: "브라질리아",
    engCapital: "Brasilia",
    continent: "남아메리카",
    location: "남아메리카 동부에 위치",
    trivia: "세계 최대 열대우림 아마존과 화려한 쌈바 카니발 축제, 리우 해안의 거대 거대 예수 그리스도상으로 유명합니다.",
    landmarks: ["리우 예수 구원자상", "이구아수 폭포", "아마존 우림"]
  },
  {
    code: "ar",
    name: "아르헨티나",
    engName: "Argentina",
    capital: "부엔오스아이레스",
    engCapital: "Buenos Aires",
    continent: "남아메리카",
    location: "남아메리카 남부에 위치",
    trivia: "열정적인 춤 탱고와 소고기 숯불구이 아사도, 그리고 국토 남쪽 끝 파타고니아 빙하가 장관입니다.",
    landmarks: ["페리토 모레노 빙하", "부에노스아이레스 라보카 거리", "이구아수 폭포"]
  },
  {
    code: "co",
    name: "콜롬비아",
    engName: "Colombia",
    capital: "보고타",
    engCapital: "Bogota",
    continent: "남아메리카",
    location: "남아메리카 북서단에 위치",
    trivia: "세계 최대 고급 커피 생산국 중 하나로 수도 보고타와 파스텔톤 가옥이 보존된 카르타헤나 구도심이 아름답습니다.",
    landmarks: ["카르타헤나 성벽도시", "몬세라테 언덕"]
  },
  {
    code: "cl",
    name: "칠레",
    engName: "Chile",
    capital: "산티아고",
    engCapital: "Santiago",
    continent: "남아메리카",
    location: "남아메리카 서부 태평양 연안 국토",
    trivia: "남북으로 4,300km가 넘는 세계에서 가장 긴 국토이며 외딴 바다 위 신비로운 모아이 석상 섬이 영토입니다.",
    landmarks: ["이스터섬 모아이 석상", "토레스 델 파이네 국립공원"]
  },
  {
    code: "pe",
    name: "페루",
    engName: "Peru",
    capital: "리마",
    engCapital: "Lima",
    continent: "남아메리카",
    location: "남아메리카 서부 안데스산맥에 위치",
    trivia: "고대 안데스 잉카 제국의 공중 도시 마추픽추 유적과 하늘 높은 곳에서만 보이는 나스카 지상화가 유명합니다.",
    landmarks: ["마추픽추 공중도시", "쿠스코 잉카 옛수도", "나스카 라인 지상화"]
  },
  {
    code: "ve",
    name: "베네수엘라",
    engName: "Venezuela",
    capital: "카라카스",
    engCapital: "Caracas",
    continent: "남아메리카",
    location: "남아메리카 최북단에 위치",
    trivia: "세계에서 가장 긴 높이(979m)에서 쏟아져 내리는 앤젤 폭포(앙헬 폭포)와 막대한 석유 매장량을 자랑합니다.",
    landmarks: ["앤젤 폭포", "로라이마 테이블 마운틴"]
  },
  // [나머지 9개국]
  {
    code: "bo",
    name: "볼리비아",
    engName: "Bolivia",
    capital: "수크레",
    engCapital: "Sucre",
    continent: "남아메리카",
    location: "남아메리카 중앙 내륙 고원 지대",
    trivia: "비가 오면 하늘 전체가 비치는 거대한 '우유니 소금 사막'과 해발 3,800m의 구름 위 티티카카 호수가 상징입니다.",
    landmarks: ["우유니 소금사막", "티티카카 호수 (갈대섬)"]
  },
  {
    code: "ec",
    name: "에콰도르",
    engName: "Ecuador",
    capital: "키토",
    engCapital: "Quito",
    continent: "남아메리카",
    location: "남아메리카 북서부 적도 선상 위치",
    trivia: "국명 자체가 적도(Ecuador)이며 다윈의 진화론 영감을 준 독특한 동물들의 보고 갈라파고스 제도가 영토입니다.",
    landmarks: ["갈라파고스 제도", "키토 적도기념비 광장"]
  },
  {
    code: "gy",
    name: "가이아나",
    engName: "Guyana",
    capital: "조지타운",
    engCapital: "Georgetown",
    continent: "남아메리카",
    location: "남아메리카 북부 대서양 연안",
    trivia: "영어를 국어로 사용하며 울창한 아마존 계통 밀림 속에 웅장하게 떨어지는 카이에투르 폭포가 명물입니다.",
    landmarks: ["카이에투르 폭포", "조지타운 나무 대성당"]
  },
  {
    code: "py",
    name: "파라과이",
    engName: "Paraguay",
    capital: "아순시온",
    engCapital: "Asuncion",
    continent: "남아메리카",
    location: "남아메리카 남부 중앙 내륙 위치",
    trivia: "바다가 없는 내륙국이나 강과 운하가 발달했고 세계 최대 이타이푸 수력발전 댐을 브라질과 공동 소유하고 있습니다.",
    landmarks: ["이타이푸 수력발전댐", "아순시온 독립 기념관"]
  },
  {
    code: "sr",
    name: "수리남",
    engName: "Suriname",
    capital: "파라마리보",
    engCapital: "Paramaribo",
    continent: "남아메리카",
    location: "남아메리카 북동부 가이아나 동쪽",
    trivia: "네덜란드 지배를 받아 유럽식 목조 가옥이 파라마리보 도심에 가득하며 정글 속 풍부한 야생 생태계를 보존하고 있습니다.",
    landmarks: ["파라마리보 목조 옛도심", "브라운스버그 국립공원"]
  },
  {
    code: "uy",
    name: "우루과이",
    engName: "Uruguay",
    capital: "몬테비데오",
    engCapital: "Montevideo",
    continent: "남아메리카",
    location: "브라질과 아르헨티나 사이 남서부",
    trivia: "남미에서 삶의 질이 안정적이며 세계 최초의 1회 월드컵 개최국이자 아름다운 등대 요새 콜로니아가 유명합니다.",
    landmarks: ["콜로니아 델 새크라멘토 요새", "몬테비데오 헌법광장"]
  },
  {
    code: "fk",
    name: "포클랜드 제도",
    engName: "Falkland Islands",
    capital: "스탠리",
    engCapital: "Stanley",
    continent: "남아메리카",
    location: "아르헨티나 동남쪽 대서양 남단 섬들",
    trivia: "영국령 자치 영토로 양 방목이 주 산업이며 해안가를 따라 무리 지어 귀엽게 서식하는 남극 펭귄들이 명물입니다.",
    landmarks: ["스탠리 지포 해변 펭귄 서식지", "크라이스트처치 대성당"]
  },
  {
    code: "gf",
    name: "프랑스령 기아나",
    engName: "French Guiana",
    capital: "카옌",
    engCapital: "Cayenne",
    continent: "남아메리카",
    location: "남아메리카 북동부 브라질 북서쪽",
    trivia: "남미에 남은 프랑스 영토이며, 기후가 온화하고 적도에 가까워 유럽 우주국의 기아나 우주 센터가 위치하고 있습니다.",
    landmarks: ["쿠루 유럽 우주센터 발사장", "악마의 섬 구수용소"]
  },
  {
    code: "gs",
    name: "사우스조지아 제도",
    engName: "South Georgia Islands",
    capital: "그리트비켄",
    engCapital: "Grytviken",
    continent: "남아메리카",
    location: "남대서양 극지방 부근 섬나라",
    trivia: "거의 무인도에 가까운 영국령 남극 전초기지 섬으로 수십만 마리의 임금펭귄과 물개들이 섬 해변을 빽빽이 채웁니다.",
    landmarks: ["그리트비켄 옛포경기지 & 섀클턴 무덤", "골드 하버 펭귄무리지"]
  },

  // ==========================================
  // --- 아프리카 (Africa) - 총 55개국 ---
  // ==========================================
  // [주요국 9개국 선두 배치]
  {
    code: "eg",
    name: "이집트",
    engName: "Egypt",
    capital: "카이로",
    engCapital: "Cairo",
    continent: "아프리카",
    location: "아프리카 북동부 홍해 연안에 위치",
    trivia: "세계 4대 문명 발상지이며, 사막 사구 위에 굳건히 세워진 피라미드와 스핑크스, 웅장한 신전 유적이 가득합니다.",
    landmarks: ["기자 대피라미드", "스핑크스", "아부심벨 신전"]
  },
  {
    code: "za",
    name: "남아프리카 공화국",
    engName: "South Africa",
    capital: "프리토리아",
    engCapital: "Pretoria",
    continent: "아프리카",
    location: "아프리카 대륙 최남단에 위치",
    trivia: "만델라 대통령으로 상징되는 민주주의 극복의 역사와 케이프타운 뒤편의 거대 절벽 테이블마운틴이 랜드마크입니다.",
    landmarks: ["테이블 마운틴", "희망봉", "크루거 국립공원"]
  },
  {
    code: "ke",
    name: "케냐",
    engName: "Kenya",
    capital: "나이로비",
    engCapital: "Nairobi",
    continent: "아프리카",
    location: "동아프리카 인도양 연안 적도 선상",
    trivia: "드넓은 초원 사바나에서 마사이족 전통 부족과 수많은 얼룩말, 야생 사자가 뛰어노는 사파리 관광의 성지입니다.",
    landmarks: ["마사이마라 국립보호구", "나쿠루 호수 (홍학)", "암보셀리 국립공원"]
  },
  {
    code: "ng",
    name: "나이지리아",
    engName: "Nigeria",
    capital: "아부자",
    engCapital: "Abuja",
    continent: "아프리카",
    location: "서아시아 기니만 연안에 위치",
    trivia: "아프리카 최대 인구 대국이자 대규모 유전 석유 수출국으로 활기 넘치는 아프리카 문화 예술의 중심지입니다.",
    landmarks: ["주마 락 바위산", "나이지리아 국립박물관"]
  },
  {
    code: "ma",
    name: "모로코",
    engName: "Morocco",
    capital: "라바트",
    engCapital: "Rabat",
    continent: "아프리카",
    location: "아프리카 북서단 지중해 연안",
    trivia: "온 도시 골목이 온통 푸른 파스텔톤인 셰프샤우엔 마을과 가죽 염색 공장 테너리가 있는 전통 아랍 요새 도시입니다.",
    landmarks: ["셰프샤우엔 파란마을", "마라케시 메디나 전통광장", "페스 가죽염색터"]
  },
  {
    code: "dz",
    name: "알제리",
    engName: "Algeria",
    capital: "알제",
    engCapital: "Algiers",
    continent: "아프리카",
    location: "지중해 남부 북아프리카에 위치",
    trivia: "아프리카에서 면적이 가장 큰 나라이며 국토의 80% 이상이 끝없는 모래 폭풍이 몰아치는 사하라 사막 지대입니다.",
    landmarks: ["노트르담 다프리크 성당", "제밀라 로마유적"]
  },
  {
    code: "et",
    name: "에티오피아",
    engName: "Ethiopia",
    capital: "아디스아바바",
    engCapital: "Addis Ababa",
    continent: "아프리카",
    location: "동아프리카 고원 지대에 위치",
    trivia: "향기로운 커피 원산지(예가체프)로 유명하며, 절벽 바위를 깎아 지하에 조각해 만든 라리벨라 석굴교회가 신비롭습니다.",
    landmarks: ["라리벨라 암굴 교회군", "시미엔 국립공원"]
  },
  {
    code: "gh",
    name: "가나",
    engName: "Ghana",
    capital: "아크라",
    engCapital: "Accra",
    continent: "아프리카",
    location: "서아프리카 기니만 연안에 위치",
    trivia: "우리가 먹는 초콜릿의 원료인 카카오 열매가 풍부하게 재배되며 과거 금 무역이 활발해 황금해안으로 불렸습니다.",
    landmarks: ["카쿰 국립공원 (흔들다리)", "엘미나 성채 옛노예성"]
  },
  {
    code: "tz",
    name: "탄자니아",
    engName: "Tanzania",
    capital: "도도마",
    engCapital: "Dodoma",
    continent: "아프리카",
    location: "동아프리카 인도양 연안에 위치",
    trivia: "아프리카 최고봉 만년설 킬리만자로산과 수백만 야생동물 대이동이 일어나는 세렝게티 국립공원을 품고 있습니다.",
    landmarks: ["킬리만자로산", "세렝게티 국립공원", "잔지바르 스톤타운 섬"]
  },
  // [나머지 46개국]
  {
    code: "ao",
    name: "앙골라",
    engName: "Angola",
    capital: "루안다",
    engCapital: "Luanda",
    continent: "아프리카",
    location: "남서부 아프리카 대서양 연안",
    trivia: "석유와 다이아몬드 광물이 가득한 자원 대국이며 깎아지른 바위 기둥 절벽인 블랙 락스가 기묘한 자연을 연출합니다.",
    landmarks: ["칼란둘라 거대폭포", "풍고 안동고 블랙 락스"]
  },
  {
    code: "bf",
    name: "부르키나파소",
    engName: "Burkina Faso",
    capital: "와가두구",
    engCapital: "Ouagadougou",
    continent: "아프리카",
    location: "서아프리카 말리 남쪽에 위치",
    trivia: "사바나 기후대로 흙과 나뭇가지로 진흙 예술 성채 모스크를 지었으며, 아프리카 최대 영화제 FESPACO 개최지입니다.",
    landmarks: ["보보디울라소 대모스크", "로로페니 돌 성벽유적"]
  },
  {
    code: "bi",
    name: "부룬디",
    engName: "Burundi",
    capital: "기테가",
    engCapital: "Gitega",
    continent: "아프리카",
    location: "동아프리카 탕가니카 호수 북쪽",
    trivia: "세계에서 가장 깊고 긴 호수인 탕가니카 호수를 접하고 있으며 힘 있고 웅장한 왕실 둥둥 북 연주가 문화 상징입니다.",
    landmarks: ["기테가 국립박물관", "탕가니카 호수 전망대"]
  },
  {
    code: "bj",
    name: "베냉",
    engName: "Benin",
    capital: "포르토노보",
    engCapital: "Porto-Novo",
    continent: "아프리카",
    location: "서아프리카 기니만 나이지리아 서쪽",
    trivia: "부두교 신앙의 탄생지이며 노예 무역의 비극이 서린 역사의 해안 '돌아올 수 없는 문' 성채가 해안에 서 있습니다.",
    landmarks: ["돌아올 수 없는 문 (위다)", "간비에 수상가옥 마을"]
  },
  {
    code: "bw",
    name: "보츠와나",
    engName: "Botswana",
    capital: "가보로네",
    engCapital: "Gaborone",
    continent: "아프리카",
    location: "남부 아프리카 칼라하리 사막 근처",
    trivia: "사막 한가운데 강물이 스며들어 거대한 늪지대 생태계를 이루는 '오카방고 델타'와 다이아몬드로 경제가 안정적입니다.",
    landmarks: ["오카방고 델타 습지", "초베 국립공원 (코끼리떼)"]
  },
  {
    code: "cd",
    name: "콩고민주공화국",
    engName: "DR Congo",
    capital: "킨샤사",
    engCapital: "Kinshasa",
    continent: "아프리카",
    location: "아프리카 대륙 한가운데 분지에 위치",
    trivia: "거대한 콩고강 열대우림을 끼고 있으며 활화산 킬라웨어 니라공고 산꼭대기 붉은 용암 호수가 끓어오릅니다.",
    landmarks: ["니라공고 화산 용암호", "비룽가 국립공원 (마운틴고릴라)"]
  },
  {
    code: "cf",
    name: "중앙아프리카공화국",
    engName: "Central African Republic",
    capital: "방기",
    engCapital: "Bangui",
    continent: "아프리카",
    location: "아프리카 대륙 지리적 중앙 내륙 위치",
    trivia: "울창한 정글 숲을 무대로 원시 피그미 부족의 문화 전통이 보존되어 있고 희귀한 아프리카 숲코끼리들이 모여듭니다.",
    landmarks: ["장가 상가 국립공원", "방기 우방기 강변"]
  },
  {
    code: "cg",
    name: "콩고공화국",
    engName: "Congo Republic",
    capital: "브라자빌",
    engCapital: "Brazzaville",
    continent: "아프리카",
    location: "콩고강 서쪽 연안 중서부 아프리카",
    trivia: "강을 사이에 두고 콩고민주공화국 수도 킨샤사와 마주 보며, 정교하고 값비싼 명품 정장을 차려입는 신사 사페르가 유명합니다.",
    landmarks: ["브라자빌 바실리카 성당", "레시오 루나 고릴라보호구"]
  },
  {
    code: "ci",
    name: "코트디부아르",
    engName: "Ivory Coast",
    capital: "야무수크로",
    engCapital: "Yamoussoukro",
    continent: "아프리카",
    location: "서아프리카 라이베리아 동쪽 연안",
    trivia: "세계 최대 카카오 수출국이며 수도 야무수크로에 바티칸을 본떠 지은 세계 최고 크기의 거대 성모 대성당이 위용을 뽐냅니다.",
    landmarks: ["평화의 성모 대성당", "아비장 타요 국립공원"]
  },
  {
    code: "cm",
    name: "카메룬",
    engName: "Cameroon",
    capital: "야운데",
    engCapital: "Yaounde",
    continent: "아프리카",
    location: "중서부 아프리카 기니만 연안",
    trivia: "아프리카의 축소판이라 불릴 만큼 해변, 정글, 사막, 산악 기후가 다 있으며 서부 아프리카 최고봉 카메룬산이 솟아 있습니다.",
    landmarks: ["카메룬 활화산 산맥", "자 생물보존지 국립공원"]
  },
  {
    code: "cv",
    name: "카보베르데",
    engName: "Cape Verde",
    capital: "프라이아",
    engCapital: "Praia",
    continent: "아프리카",
    location: "서아프리카 세네갈 서쪽 대서양 섬나라",
    trivia: "포르투갈풍의 이국적 가옥과 화산 분화구 지형이 어우러진 평화로운 섬나라로 아름다운 모라 음악이 탄생한 곳입니다.",
    landmarks: ["포구 활화산 분화구마을", "시다데 벨랴 역사지구"]
  },
  {
    code: "dj",
    name: "지부티",
    engName: "Djibouti",
    capital: "지부티",
    engCapital: "Djibouti",
    continent: "아프리카",
    location: "동아프리카 아덴만 소말리아 북쪽",
    trivia: "아프리카 대륙에서 가장 낮고 염분이 사해만큼 높은 아살 호수가 있으며 홍해 입구의 중요한 군사 요충지입니다.",
    landmarks: ["아살 소금호수", "아베 호수 (굴뚝 흙기둥)"]
  },
  {
    code: "er",
    name: "에리트레아",
    engName: "Eritrea",
    capital: "아스마라",
    engCapital: "Asmara",
    continent: "아프리카",
    location: "동아프리카 홍해 연안 수단 동쪽",
    trivia: "이탈리아 식민 지배를 받아 수도 아스마라 전체에 고풍스러운 1930년대풍 아르데코 유럽식 건축물이 잘 남은 숨은 소국입니다.",
    landmarks: ["아스마라 아르데코 유산거리", "홍해 다할락 제도 산호초"]
  },
  {
    code: "ga",
    name: "가봉",
    engName: "Gabon",
    capital: "리브르빌",
    engCapital: "Libreville",
    continent: "아프리카",
    location: "중서부 아프리카 적도 선상 대서양 연안",
    trivia: "국토의 대부분이 태고의 적도 열대우림이며, 야생 코끼리가 에메랄드 해변가를 유유히 걷는 신비한 해안 국립공원이 있습니다.",
    landmarks: ["로앙고 국립공원 (해변 숲코끼리)", "퐁고 국립공원"]
  },
  {
    code: "gm",
    name: "감비아",
    engName: "Gambia",
    capital: "반줄",
    engCapital: "Banjul",
    continent: "아프리카",
    location: "서아프리카 감비아 강변을 따라 위치",
    trivia: "세네갈 내부에 감비아 강줄기를 감싸듯이 위치한 좁고 기다란 영토의 나라로 수많은 철새가 날아드는 탐조 천국입니다.",
    landmarks: ["감비아강 국립공원", "제임스 섬 옛노예성"]
  },
  {
    code: "gn",
    name: "기니",
    engName: "Guinea",
    capital: "코나크리",
    engCapital: "Conakry",
    continent: "아프리카",
    location: "서아프리카 대서양 연안 시에라리온 북쪽",
    trivia: "서아프리카의 젖줄인 니제르강과 세네갈강이 발원하는 웅장한 푼타잘론 고원 폭포 지대를 품고 있는 원시 자연 국가입니다.",
    landmarks: ["푼타잘론 고원 폭포군", "님바산 자연보존지구"]
  },
  {
    code: "gq",
    name: "적도 기니",
    engName: "Equatorial Guinea",
    capital: "말라보",
    engCapital: "Malabo",
    continent: "아프리카",
    location: "중서부 아프리카 가봉 북쪽 기니만",
    trivia: "수도는 대륙이 아닌 비오코 섬에 있고 스페인어를 쓰는 유일한 아프리카 국가이며 대규모 해상 석유 생산으로 부유합니다.",
    landmarks: ["말라보 대성당", "비오코섬 로바 활화산 칼데라"]
  },
  {
    code: "gw",
    name: "기니비사우",
    engName: "Guinea-Bissau",
    capital: "비사우",
    engCapital: "Bissau",
    continent: "아프리카",
    location: "서아프리카 세네갈 남쪽 기니 북쪽",
    trivia: "수로가 얽힌 갯벌 델타 습지와 포르투갈 풍 가옥이 어우러진 해안 비조고스 제도에 희귀 해양 하마가 서식합니다.",
    landmarks: ["비조고스 제도 군도생태계", "비사우 올드 포트 항구"]
  },
  {
    code: "lr",
    name: "라이베리아",
    engName: "Liberia",
    capital: "몬로비아",
    engCapital: "Monrovia",
    continent: "아프리카",
    location: "서아프리카 대서양 코트디부아르 서쪽",
    trivia: "19세기 미국에서 해방된 흑인 노예들이 아프리카로 돌아와 세운 자유 공화국으로 거대 고무 플랜테이션이 발달했습니다.",
    landmarks: ["몬로비아 국립박물관", "사포 국립공원 열대우림"]
  },
  {
    code: "ls",
    name: "레소토",
    engName: "Lesotho",
    capital: "마세루",
    engCapital: "Maseru",
    continent: "아프리카",
    location: "남아공 영토 내부에 완전히 둘러싸인 나라",
    trivia: "국토 전체가 해발 1,400m 이상인 고산 지대로 '하늘의 왕국'이라 불리며, 겨울에는 아프리카 최초의 눈 덮인 스키장이 개장합니다.",
    landmarks: ["아프리스키 리조트", "말레추냐네 웅장한 절벽폭포"]
  },
  {
    code: "ly",
    name: "리비아",
    engName: "Libya",
    capital: "트리폴리",
    engCapital: "Tripoli",
    continent: "아프리카",
    location: "북아프리카 지중해 연안 이집트 서쪽",
    trivia: "사하라 사막 중심부에 세워진 오아시스 진흙 도시 가다메스와 지중해 연안 로마 식민지 거대 렙티스 마그나 유적이 훌륭합니다.",
    landmarks: ["렙티스 마그나 로마유적", "가다메스 사막오아시스 점토도시"]
  },
  {
    code: "mg",
    name: "마다가스카르",
    engName: "Madagascar",
    capital: "안타나나리보",
    engCapital: "Antananarivo",
    continent: "아프리카",
    location: "동아프리카 남동부 인도양의 거대 섬나라",
    trivia: "세계에서 네 번째로 큰 섬으로, 하늘로 가지를 뻗은 신비로운 바오바브나무 거리와 여우원숭이 등 독특한 생태계가 살아있습니다.",
    landmarks: ["바오바브나무 거리", "칭기 드 베마라하 바위바늘 국립공원"]
  },
  {
    code: "ml",
    name: "말리",
    engName: "Mali",
    capital: "바마코",
    engCapital: "Bamako",
    continent: "아프리카",
    location: "서아프리카 사하라 사막 남부 내륙",
    trivia: "과거 황금 무역의 거점으로 흙과 나무로 지은 세계 최대 진흙 건축물 젠네 대모스크와 사막 무역 도시 팀북투가 상징입니다.",
    landmarks: ["젠네 대모스크", "팀북투 오아시스 서고유적"]
  },
  {
    code: "mr",
    name: "모리타니",
    engName: "Mauritania",
    capital: "누악쇼트",
    engCapital: "Nouakchott",
    continent: "아프리카",
    location: "서아프리카 대서양 연안 사하라 사막 서단",
    trivia: "황량한 사막 한가운데 위성에서만 뚜렷하게 관측되는 거대한 동심원 지형인 '사하라의 눈(리샤트 구조)'이 신비롭습니다.",
    landmarks: ["사하라의 눈 (리샤트 구조)", "싱게티 고대 도서관"]
  },
  {
    code: "mu",
    name: "모리셔스",
    engName: "Mauritius",
    capital: "포트루이스",
    engCapital: "Port Louis",
    continent: "아프리카",
    location: "마다가스카르 동쪽 인도양 섬나라",
    trivia: "소설가 마크 트웨인이 천국이 이곳을 본떠 만들어졌다고 극찬하였으며, 바닷속 소용돌이 '수중 폭포' 착시 비경이 경이롭습니다.",
    landmarks: ["샤마렐 7색조 흙언덕 & 수중 폭포", "일오세프 섬 해변"]
  },
  {
    code: "mw",
    name: "말라위",
    engName: "Malawi",
    capital: "릴롱궤",
    engCapital: "Lilongwe",
    continent: "아프리카",
    location: "동남부 아프리카 모잠비크 서북쪽",
    trivia: "국토의 큰 부분을 채운 거대 말라위 호수가 있으며, 전 세계에서 시클리드 열대 물고기 종류가 가장 많이 사는 호수입니다.",
    landmarks: ["말라위 호수 국립공원", "좀바 고원"]
  },
  {
    code: "mz",
    name: "모잠비크",
    engName: "Mozambique",
    capital: "마푸투",
    engCapital: "Maputo",
    continent: "아프리카",
    location: "남동부 아프리카 인도양 연안 마다가스카르 맞은편",
    trivia: "산호 섬 위에 세운 포르투갈 식민 도시인 모잠비크 섬 성채와 인도양 해안가의 낭만적인 에메랄드빛 해변이 아름답습니다.",
    landmarks: ["모잠비크 섬 옛요새성채", "바자루토 제도 해양공원"]
  },
  {
    code: "na",
    name: "나미비아",
    engName: "Namibia",
    capital: "빈트후크",
    engCapital: "Windhoek",
    continent: "아프리카",
    location: "남서부 아프리카 대서양 연안 남아공 북쪽",
    trivia: "붉은색 모래 언덕 사구가 대서양 해안과 만나고, 메마른 소금 분지 고목이 기묘한 예술을 이루는 데드블레이가 상징입니다.",
    landmarks: ["소서스블레이 붉은사구 & 데드블레이 고목", "에토샤 국립공원"]
  },
  {
    code: "ne",
    name: "니제르",
    engName: "Niger",
    capital: "니아메",
    engCapital: "Niamey",
    continent: "아프리카",
    location: "서아프리카 사하라 사막 한가운데 위치",
    trivia: "사막 유목 부족 투아레그족의 오랜 교두보 도시인 아가데즈 흙탑 모스크와 건조한 사막 속 공룡 화석이 자주 발견되는 사막국입니다.",
    landmarks: ["아가데즈 진흙 미나레트 모스크", "W 국립공원 사바나"]
  },
  {
    code: "rw",
    name: "르완다",
    engName: "Rwanda",
    capital: "키갈리",
    engCapital: "Kigali",
    continent: "아프리카",
    location: "동아프리카 중앙 내륙 고원 지대",
    trivia: "아픔을 극복하고 아프리카에서 가장 깨끗하고 안전한 IT 성장국이 되었으며 안개 낀 숲속 마운틴고릴라 생태계가 신비합니다.",
    landmarks: ["화산 국립공원 (마운틴고릴라)", "키부 호수 요양지"]
  },
  {
    code: "sd",
    name: "수단",
    engName: "Sudan",
    capital: "하르툼",
    engCapital: "Khartoum",
    continent: "아프리카",
    location: "이집트 남부 아프리카 동북부 위치",
    trivia: "이집트보다 경사가 급하고 아담한 크기의 고대 누비아 피라미드 무덤이 붉은 사막 사구에 200여 개 빽빽이 솟아 있습니다.",
    landmarks: ["메로에 누비아 피라미드군", "하르툼 청나일강 합류지"]
  },
  {
    code: "sl",
    name: "시에라리온",
    engName: "Sierra Leone",
    capital: "프리타운",
    engCapital: "Freetown",
    continent: "아프리카",
    location: "서아프리카 대서양 기니 남쪽 위치",
    trivia: "해방 노예들이 세운 자유의 도시 프리타운을 가졌으며 최고 품질의 보석 다이아몬드가 매장된 해안 국가입니다.",
    landmarks: ["바나나 섬 해변", "타쿠가마 침팬지 보호구역"]
  },
  {
    code: "sn",
    name: "세네갈",
    engName: "Senegal",
    capital: "다카",
    engCapital: "Dakar",
    continent: "아프리카",
    location: "아프리카 대륙 최서단 대서양 연안",
    trivia: "과거 다카르 랠리 자동차 경주의 종착지였으며, 박테리아 작용으로 물빛이 핑크 우유빛을 띠는 레트바 호수(장미호수)가 유명합니다.",
    landmarks: ["레트바 핑크장미 호수", "고레 섬 옛노예성"]
  },
  {
    code: "so",
    name: "소말리아",
    engName: "Somalia",
    capital: "모가디슈",
    engCapital: "Mogadishu",
    continent: "아프리카",
    location: "동아프리카 '아프리카의 뿔' 반도 돌출 지역",
    trivia: "대륙에서 가장 긴 긴 해안선을 가졌으며 고대 유목민들이 동굴에 남겨 놓은 형형색색의 동굴 암각화 라스 겔이 가치 높습니다.",
    landmarks: ["라스 겔 동굴 벽화유적", "모가디슈 해안선"]
  },
  {
    code: "ss",
    name: "남수단",
    engName: "South Sudan",
    capital: "주바",
    engCapital: "Juba",
    continent: "아프리카",
    location: "수단 남동부 중앙 아프리카에 위치",
    trivia: "2011년 수단으로부터 치열하게 분리 독립한 세계 최신 신생국 중 하나로 세계 최대 규모의 거대 늪지대 수드가 있습니다.",
    landmarks: ["수드 거대 내륙늪지대", "주바 백나일강 다리"]
  },
  {
    code: "sz",
    name: "에스와티니",
    engName: "Eswatini",
    capital: "음바바네",
    engCapital: "Mbabane",
    continent: "아프리카",
    location: "남아공 동남부 모잠비크 국경선에 인접",
    trivia: "과거 스와질란드로 불렸던 아프리카의 마지막 군주제 국가로 매년 갈대잎 춤 축제인 리드 댄스(음랑가)가 성대히 열립니다.",
    landmarks: ["밀와네 야생동물보호구", "에줄위니 계곡문화공원"]
  },
  {
    code: "td",
    name: "차드",
    engName: "Chad",
    capital: "은자메나",
    engCapital: "N'Djamena",
    continent: "아프리카",
    location: "중앙아프리카 사하라 사막 중부 위치",
    trivia: "사막 한가운데 모래 기둥과 기묘한 돌 성채 요새가 숲을 이룬 에네디 협곡 자연과 거대 소금호수 차드 호가 있습니다.",
    landmarks: ["에네디 사막바위 협곡요새", "차드 소금호수"]
  },
  {
    code: "tg",
    name: "토고",
    engName: "Togo",
    capital: "로메",
    engCapital: "Lome",
    continent: "아프리카",
    location: "서아프리카 기니만 가나 동쪽에 위치",
    trivia: "남북으로 가늘고 긴 영토를 가진 작은 나라로, 수도 로메의 부두교 전통 치료 악마 시장(아쿠데세와 시장)이 명물입니다.",
    landmarks: ["아쿠데세와 전통 부두교 주술시장", "쿠타마쿠 진흙성채마을"]
  },
  {
    code: "tn",
    name: "튀니지",
    engName: "Tunisia",
    capital: "튀니스",
    engCapital: "Tunis",
    continent: "아프리카",
    location: "북아프리카 지중해 연안 중앙에 위치",
    trivia: "과거 로마 제국과 패권을 겨루었던 고대 카르타고 문명의 중심지이며 지중해풍 흰벽과 파란 대문의 마을이 대표적입니다.",
    landmarks: ["시디 부 사이드 파란마을", "엘젬 거대 로마콜로세움", "카르타고 고대유적지"]
  },
  {
    code: "ug",
    name: "우간다",
    engName: "Uganda",
    capital: "캄팔라",
    engCapital: "Kampala",
    continent: "아프리카",
    location: "동아프리카 거대 빅토리아 호수 북쪽 적도",
    trivia: "빅토리아 호수를 끼고 수려한 경치를 자랑하여 영국의 처칠이 '아프리카의 진주'라 격찬한 녹색 정원 국가입니다.",
    landmarks: ["머치슨 폭포 국립공원", "부위디 침팬지 숲"]
  },
  {
    code: "zm",
    name: "잠비아",
    engName: "Zambia",
    capital: "루사카",
    engCapital: "Lusaka",
    continent: "아프리카",
    location: "남부 아프리카 짐바브웨 북쪽에 위치",
    trivia: "짐바브웨 국경과 공유하는 세계 3대 폭포인 거대한 빅토리아 폭포와 웅장한 잠베지강 야생 사파리가 유명합니다.",
    landmarks: ["빅토리아 폭포", "남루앙와 국립공원"]
  },
  {
    code: "zw",
    name: "짐바브웨",
    engName: "Zimbabwe",
    capital: "하라레",
    engCapital: "Harare",
    continent: "아프리카",
    location: "남부 아프리카 남아공 북쪽에 위치",
    trivia: "거대한 돌 성벽 유적인 그레이트 짐바브웨 성과 천둥소리를 내며 떨어지는 거대 빅토리아 폭포의 본고장입니다.",
    landmarks: ["빅토리아 폭포 (악마의 풀)", "그레이트 짐바브웨 돌성벽 유적"]
  },
  {
    code: "sc",
    name: "세이셸",
    engName: "Seychelles",
    capital: "빅토리아",
    engCapital: "Victoria",
    continent: "아프리카",
    location: "마다가스카르 북동쪽 인도양의 섬나라",
    trivia: "인도양의 마지막 지상낙원이라 불리며, 거대한 화강암 바위가 백사장 해변을 장식하고 거대 거북이가 서식합니다.",
    landmarks: ["라디그 앙스 수스 다종 해변", "프랄린 국립공원 (코코 드 메르 야자수)"]
  },
  {
    code: "st",
    name: "상투메 프린시페",
    engName: "Sao Tome and Principe",
    capital: "상투메",
    engCapital: "Sao Tome",
    continent: "아프리카",
    location: "서아프리카 적도 기니만 해상의 섬나라",
    trivia: "화산 분출로 만들어진 기둥 바위가 정글 솟아 웅장함을 보이며 전통 코코아 카카오 농장이 발달한 평화로운 섬나라입니다.",
    landmarks: ["카오 그란데 화산바위기둥", "프린시페 생태보존 구역"]
  },
  {
    code: "km",
    name: "코모로",
    engName: "Comoros",
    capital: "모로니",
    engCapital: "Moroni",
    continent: "아프리카",
    location: "아프리카 동부 모잠비크 해협의 섬나라",
    trivia: "달콤한 향이 풍기는 향수 원료 일랑일랑 꽃나무가 많이 생산되는 화산섬으로 모스크와 아랍풍이 강합니다.",
    landmarks: ["카르탈라 활화산 분화구", "모로니 올드 모스크"]
  },
  {
    code: "eh",
    name: "서사하라",
    engName: "Western Sahara",
    capital: "엘아이운",
    engCapital: "Laayoune",
    continent: "아프리카",
    location: "북서아프리카 대서양 연안 모로코 남부",
    trivia: "모로코와 독립 단체 사이에 오랜 분쟁이 이어지고 있으며 황량하고 넓은 사하라 모래언덕 해안이 길게 뻗어 있습니다.",
    landmarks: ["엘아이운 그랜드 모스크", "사하라 대서양 연안 사구"]
  },

  // ==========================================
  // --- 오세아니아 (Oceania) - 총 10개국 ---
  // ==========================================
  // [주요국 4개국 선두 배치]
  {
    code: "au",
    name: "오스트레일리아",
    engName: "Australia",
    capital: "캔버라",
    engCapital: "Canberra",
    continent: "오세아니아",
    location: "남반구 오세아니아 대륙에 위치",
    trivia: "거대한 대륙 전체가 한 나라로 시드니 오페라 하우스가 랜드마크이며 캥거루와 코알라 같은 독특한 동물이 삽니다.",
    landmarks: ["시드니 오페라하우스", "그레이트 배리어 리프 (산호초)", "울루루 거대 붉은바위"]
  },
  {
    code: "nz",
    name: "뉴질랜드",
    engName: "New Zealand",
    capital: "웰링턴",
    engCapital: "Wellington",
    continent: "오세아니아",
    location: "오스트레일리아 동남부 태평양 섬나라",
    trivia: "북섬과 남섬의 화산 지형과 광활한 양 목장, 원주민 마오리족의 민속 춤 하카 전통이 유명합니다.",
    landmarks: ["밀포드 사운드 피오르", "호비튼 영화 세트장", "로토루아 유황온천지대"]
  },
  {
    code: "fj",
    name: "피지",
    engName: "Fiji",
    capital: "수바",
    engCapital: "Suva",
    continent: "오세아니아",
    location: "남태평양 멜라네시아 제도의 섬나라",
    trivia: "300여 개의 아름다운 산호초와 화산섬으로 둘러싸여 세계인들이 동경하는 남태평양 천국의 휴양지입니다.",
    landmarks: ["데나라우 리조트 해안", "싱가토카 거대 사구공원"]
  },
  {
    code: "pw",
    name: "팔라우",
    engName: "Palau",
    capital: "응게룰무드",
    engCapital: "Ngerulmud",
    continent: "오세아니아",
    location: "태평양 서부 미크로네시아의 섬나라",
    trivia: "독이 없어 안전한 수백만 마리 야광 해파리와 헤엄치는 해파리 호수(젤리피쉬 레이크)와 산호 락 아일랜드가 신비롭습니다.",
    landmarks: ["젤리피쉬 레이크 (해파리 호수)", "락 아일랜드 산호숲"]
  },
  // [나머지 6개국]
  {
    code: "pg",
    name: "파푸아뉴기니",
    engName: "Papua New Guinea",
    capital: "포트모르즈비",
    engCapital: "Port Moresby",
    continent: "오세아니아",
    location: "남태평양 뉴기니섬 동반부에 위치",
    trivia: "수백 개의 정글 속 고유 부족과 원시 부족 전통 언어들이 보존되어 전통 머드맨 진흙 가면 춤이 독특합니다.",
    landmarks: ["포트모르즈비 야생 자연공원", "밀네 베이 산호초 해역"]
  },
  {
    code: "sb",
    name: "솔로몬 제도",
    engName: "Solomon Islands",
    capital: "호니아라",
    engCapital: "Honiara",
    continent: "오세아니아",
    location: "오스트레일리아 동북쪽 태평양 섬나라",
    trivia: "과거 태평양 격전지 역사 속에 바다에 가라앉은 군함 다이빙 관광과 울창한 열대 다도해를 가졌습니다.",
    landmarks: ["과달카날 전쟁기념관", "케네디 섬 스노클링"]
  },
  {
    code: "vu",
    name: "바누아투",
    engName: "Vanuatu",
    capital: "포트빌라",
    engCapital: "Port Vila",
    continent: "오세아니아",
    location: "남태평양 멜라네시아 섬나라",
    trivia: "전통 성인식인 나무 덩굴 발목 번지점프의 기원지이며, 세계에서 가장 가까이 분화구에 갈 수 있는 활화산이 서 있습니다.",
    landmarks: ["야수르 활화산 분화구", "블루 홀 블루라군"]
  },
  {
    code: "ws",
    name: "사모아",
    engName: "Samoa",
    capital: "아피아",
    engCapital: "Apia",
    continent: "오세아니아",
    location: "남태평양 폴리네시아 제도에 위치",
    trivia: "원시 화산 암반이 붕괴하여 만들어진 둥근 천연 바다 풀장인 '토수아 오션 트렌치' 해수가 매우 맑고 아름답습니다.",
    landmarks: ["토수아 오션 트렌치 천연풀", "랄로마누 해변 백사장"]
  },
  {
    code: "to",
    name: "통가",
    engName: "Tonga",
    capital: "누쿠알로파",
    engCapital: "Nuku'alofa",
    continent: "오세아니아",
    location: "남태평양 폴리네시아 지역의 왕국",
    trivia: "태평양의 마지막 남은 전형적 부족 왕정 군주국으로 거대한 고대 돌 거석 유적과 바다 위 혹등고래 떼가 장관입니다.",
    landmarks: ["하아몽가 아 마우이 석조 거석", "혹등고래 생태관광 해역"]
  },
  {
    code: "mh",
    name: "마셜 제도",
    engName: "Marshall Islands",
    capital: "마주로",
    engCapital: "Majuro",
    continent: "오세아니아",
    location: "태평양 서부 미크로네시아 환초섬들",
    trivia: "길고 얇은 고리 모양으로 이어진 에메랄드 산호 환초섬들이며 스쿠버 다이빙 매니아들의 최고 성지 중 하나입니다.",
    landmarks: ["마주로 산호초 환초해안", "아르노 환초 피싱코스"]
  }
];
